### ISSUE TITLE
Office Hours Thursday at 4:00pm

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#10]
There will be office hours with Bob Kanuri Thursday, January 7th at 4:00pm.  They will be held in Young 306 (the computer lab).

**Comment by JRam13** [comment]
I could also do office hours on Friday evening, around 6:30ish. 

-Jonny

**Comment by bobby-digital-23** [comment]
Hi,

If anybody is running late today and needs a little more time please contact me. 

bobkanuri+github@gmail.com
(You can remove the +github part of the email but either will work - that's just to annoy spambots 😉)

Best,
Bobby
