### ISSUE TITLE
Open and Closed Comments in Github API

### ISSUE THREAD

**Issue by ronmexico15** [uchicago-mobi/2015-Winter-Forum#100]
I'm having a tough time finding the data for the count of open and closed comments in the github api.

From the documentation (https://developer.github.com/v3/issues/), it looks like there should be a "closed_issues" and an "open_issues" attribute, but I'm not seeing it here: https://api.github.com/repos/uchicago-mobi/2015-Winter-Forum/issues. Is anyone else having a similar issue?

Thanks in advance.

**Comment by JRam13** [comment]
(all isues - open issues).

**Comment by tabinks** [comment]
There are different approaches to retrieve the correct information, but you should be able to get it through a combination of these URLs:

``` objc
NSString *url = @"https://api.github.com/repos/uchicago-mobi/2015-Winter-Forum/issues?state=open";
NSString *url = @"https://api.github.com/repos/uchicago-mobi/2015-Winter-Forum/issues?state=closed";
NSString *url = @"https://api.github.com/repos/uchicago-mobi/2015-Winter-Forum/issues?state=all";
```

**Comment by JRam13** [comment]
Sorry I misread your comment. To get open issues you call 

```
https://api.github.com/repos/uchicago-mobi/2015-Winter-Forum/issues?state=open.
```

And for all you change the state to 'all'. For closed issues change it to 'close'.

**Comment by JRam13** [comment]
I fail at github today.

**Comment by tabinks** [comment]
We're all friends now, yo.

**Comment by ronmexico15** [comment]
Thanks, I got it to work just doing a count.

It seems like the documentation showed attributes that had a count of the open/closed issues, though.
