### ISSUE TITLE
Issues with NSMutableArray in CircleViewController

### ISSUE THREAD

**Issue by hwealnegn** [uchicago-mobi/2015-Winter-Forum#101]
I'm using the same code (i.e. copied and pasted) I used in the TableViewControllers to obtain the JSON data , and while it shows up in my NSLog, for some reason I'm not able to use the array in my viewDidLoad method (it tells me that the array is empty*, but I can clearly see it in my log...). I think I should be able to reutilize the code in the regular ViewController (although I've removed the [self.tableVIew reloadData] line since it's no longer a TableViewController and therefore irrelevant?), so I'm not sure what the cause of the issue could be? Unless I'm wrong about being able to use the same code...
- When I call [self.issueData count] it returns 0, and I'm not able to call any of the array's contents (obviously since it thinks it's empty).

**Comment by tabinks** [comment]
You need to copy the data from the returned JSON array to a new array that is owned by the view controller (i.e. a `@property`).  The data inside a block is only scoped by that block, so it won't exist outside the block.

**Comment by JRam13** [comment]
Have you initialized your self.issueData? 

``` objc
self.issueData = [[NSMutableArray alloc] init];
```

?

**Comment by hwealnegn** [comment]
I have an NSMutableArray property "issueData" in my .h file and I've initialized self.issueData in viewDidLoad...

**Comment by JRam13** [comment]
> I have an NSMutableArray property "issueData" in my .h file and I've initialized self.issueData in viewDidLoad...

``` objc
   // GitHub API url
    NSString *url = @"https://api.github.com/repos/uchicago-mobi/2015-Winter-Forum/issues?state=open";

    // Create NSUrlSession
    NSURLSession *session = [NSURLSession sharedSession];

    // Create data download taks
    [[session dataTaskWithURL:[NSURL URLWithString:url]
            completionHandler:^(NSData *data,NSURLResponse *response,NSError *error) {

                NSError *jsonError;
                self.issueData = [NSJSONSerialization JSONObjectWithData:data
                                                                 options:NSJSONReadingAllowFragments
                                                                   error:&jsonError];
                // Log the data for debugging
                NSLog(@"DownloadeData:%@",self.issueData);

                // Use dispatch_async to update the table on the main thread
                // Remember that NSURLSession is downloading in the background
                dispatch_async(dispatch_get_main_queue(), ^{
                    //UPDATE CIRCLE HERE
                });
            }] resume];
```

Make sure you're updating your view in the right place.

**Comment by hwealnegn** [comment]
So I originally created a UILabel in my UIView and wanted to update it through my UIViewController. When I had this line in my viewDidLoad

`((CircleView *) self.view).openIssues = @"HELLO";`

the label would appear, but when I moved it under `dispatch_async` it wouldn't show up.

However, I just tried creating a UILabel in Storyboard and updating it under `dispatch_async` works (thanks!). Is there a reason it didn't work for my programmatically created UILabel in my UIView?

**Comment by JRam13** [comment]
I'm not sure what is happening in your code from your snippet.

Why are you casting self.view?
What is CircleView?
What is openIssues? A label?

I would just make a label in your storyboard and connect it as an outlet inside your CircleViewController. You can then access it and change the text inside the `dispatch_async` block by calling 
`self.mylabel.text = @"myString";`

**Comment by hwealnegn** [comment]
Sorry for the confusion!

CircleView is my UIView for the CircleViewController, from where I had drawn my circle. openIssues was the label I had created in the UIView, and I cast a self.view to update the UIView through my UIViewController.

(I think I'll stick with creating a UILabel from Storyboard and using it in CircleViewController, though.)
