### ISSUE TITLE
GitHub Formatting Tips

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#102]
When writing code in GitHub Issues you can use some simple formatting to make it easier to use.  The most useful is to wrap code in triple backticks "```" for code blocks.  Adding "objc" after will highlight the syntax.  You can also use single backticks `...` for inline code.

![image](https://cloud.githubusercontent.com/assets/93689/5992985/eeb9475c-aa05-11e4-87f6-a992d907ee6e.png)

will display as

![image](https://cloud.githubusercontent.com/assets/93689/5992986/03ac9fba-aa06-11e4-8806-3199e82f7e01.png)

or

![image](https://cloud.githubusercontent.com/assets/93689/5992987/0f674332-aa06-11e4-8bd6-de6e6a4bd9aa.png)

will display as

![image](https://cloud.githubusercontent.com/assets/93689/5992988/173c9800-aa06-11e4-8389-91cc42c0daa6.png)

For more information, see this link: https://help.github.com/articles/github-flavored-markdown/

**Comment by JRam13** [comment]
> https://help.github.com/articles/markdown-basics/
> https://help.github.com/articles/github-flavored-markdown/

Some of this stuff will not work if you comment in a Reply to an email.
