### ISSUE TITLE
Querying API Outside of Current Issue Table

### ISSUE THREAD

**Issue by gitlaura** [uchicago-mobi/2015-Winter-Forum#103]
"Pulling the table refresh should requery the API and reload the table results for both issues tables."

I'm having trouble figuring out how to update the All Issues Table and the Open Issues Table at once. I currently have the code to call the API in every controller where I want to use the data, but I think it'd be better if it was in a separate controller so I don't have to call the API as often. What's the best way to do this?

One idea - keeping the data in public instance variables (like issueData). But I don't think I'm able to call the objects to update the instance variables (like TableViewController.issueData = newIssueData).

**Comment by JRam13** [comment]
I don't think thats what it was intended to mean (but you're right in thinking that 1 tableview should update the other).

Read it as, 'For both issues tables, pulling the table refresh should requery the API and reload the table results.'

Just to clarify, each table should have the refresh option and you must refresh each table individually. 

...right Andrew?

**Comment by tabinks** [comment]
Yes, Jonny is correct.  It should be each loads the table "on that view controller".  Sorry for the confusion on this.
