### ISSUE TITLE
Office Hours - Monday 3:30pm @ Crerar - 2/2/2015

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#105]
Assuming school is not cancelled, I will be holding office hours at Crerar on Monday starting at 3:30pm.

Please let me know if you plan on attending. Check here for any last minute weather related issues.

Stay warm and stay safe during this crazy blizzard! :-)

**Comment by mceruzzi-denodo** [comment]
Very strong chance you'll see me there.

**Comment by susanstevens** [comment]
I'll probably be there!

**Comment by bobby-digital-23** [comment]
Sorry, having car issues. Pulled off side of highway,  checking car right now. :(

Update coming asap. Please bear with me.

**Comment by bobby-digital-23** [comment]
Apologies, my friends car had a hidden piece of ice lodged in the wheel well causing the car to shake at speeds above 35mph! We just dislodged the ice and are back on the highway.

Hope to be there in 20-30 min according to gps  . Sorry again.

**Comment by bobby-digital-23** [comment]
Looking for parking on campus now. 

Could you all meet me at our classroom in Ryerson in approx 10-15 min?

**Comment by bobby-digital-23** [comment]
At Ryerson
