### ISSUE TITLE
Trouble extracting author information

### ISSUE THREAD

**Issue by mceruzzi-denodo** [uchicago-mobi/2015-Winter-Forum#106]
I can extract title information from the data by using this: cell.title.text = [thread objectForKey:@"title"];
However, when I try to extract information from "login" or any of the url's using similar methods, it simply leaves me with empty labels. Anyone know why this could be?

**Comment by narvemp** [comment]
You need to look in two levels deep.

[[thread objectFortKey:"user"] objectForKey:"login"]

**Comment by mceruzzi-denodo** [comment]
^I wish this forum had a rep feature. You just made my life a million times easier. Thanks!!!
