### ISSUE TITLE
Default (nil) of text field

### ISSUE THREAD

**Issue by mattmeier** [uchicago-mobi/2015-Winter-Forum#11]
Hi,

For some reason, my text field seems to have the default value "Your Name" rather than nil, and thus I always get "Hello, Your Name!" rather than "Hello, World!" (which would show up, if the length of nameString were 0) when I click on the Hello button, i.e. although I did not enter anything by keyboard into the text field. Any suggestions on how to fix that? Thanks!

**Comment by xctom** [comment]
Maybe you should place "Your Name" in the attribute "placeholder", like this
![image](https://cloud.githubusercontent.com/assets/4891624/5670367/d66ca294-9744-11e4-9a71-7ff8e3252c11.png)

**Comment by mattmeier** [comment]
Worked, thanks!=)
