### ISSUE TITLE
Reminder - Office hours today (Friday) @ 6:00 Crerar.

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Winter-Forum#112]
![Be there!](http://www.quickmeme.com/img/2b/2b0cd568303d7674e6350d8f600d0e487a428d75501399a0d403c0fd9116ce01.jpg)

**Comment by drefiuza** [comment]
![](http://www.reactiongifs.com/r/2013/06/I-dont-believe-you.gif)

**Comment by windyita** [comment]
(╰_╯)#

**Comment by JRam13** [comment]
I'm here now.
