### ISSUE TITLE
Tips for HW5 (Tic-Tac-Toe)

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Winter-Forum#113]
• Disable Autolayouts or you'll pull your hair out trying to find out why your images/views reset to their original positions. You can also set a views translatesAutoresizingMaskIntoConstraints property to YES as an alternative.
• performSelector is a great tool if you need to delay method calls. For example:

``` objc
    [self performSelector:@selector(callThisMethodAfterTwoSeconds) withObject:nil afterDelay:2];
```

• Why aren't my images panning!!!???... 
![](http://cdn5.raywenderlich.com/wp-content/uploads/2011/11/UserInteractionEnabled.png)

• You can remove gesture recognizers on a view by calling 

``` objc
[imageView removeGestureRecognizer:yourView];
```

(I'll keep them coming as we get questions about this assignment)

**Comment by tabinks** [comment]
You can remove gesture recognizers on a view by calling `[imageView removeGestureRecognizer:yourView];`.  Depending on your implementation details, you may want to use this..of course your can also disable user interaction (as shown above).
