### ISSUE TITLE
UIPanGestureRecognizer Question.

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#114]
For some reason when I start to drag an X (or O for that matter) the translation seems to be correct, but when adding the points for the new center, there seems to be a massive jump and the X will fly off the screen.  

I'm somewhat pulling my hair out.  NSLog seems to reveal nothing either except that the "X" is taking far more massive leaps than my mouse is moving...

Any ideas would be greatly appreciated.

**Comment by narvemp** [comment]
You have to set the translation to zero (CGPointZero) after calling translation and setting center, otherwise the translation quickly increases so the pan goes offscreen.  The code in the lecture notes has an example.

**Comment by johnnypaper** [comment]
Man.  Unreal.  Thanks very much for mentioning that.  I do see that in the notes.  I was looking at the Apple docs, because the slides can get really slow moving back and forth...it is far easier for me to look through the code Apple provides in XCode.  And now I see that in the Apple code too.  _&_&_$(#_%!  I have no idea how I missed that.

Thanks Again.
