### ISSUE TITLE
Question about customized AlertView

### ISSUE THREAD

**Issue by xctom** [uchicago-mobi/2015-Winter-Forum#115]
I remember professor said in class that we only need to customize only one of three alertview. But I found it in requirement that all three should be customized. 
Can I just customized info sheet?
![image](https://cloud.githubusercontent.com/assets/4891624/6090972/533bb140-ae59-11e4-97ae-46c6d618f273.png)

**Comment by tabinks** [comment]
As a best practice (and to save yourself work), create a single custom view that serves as your alert view.  Then show this one with different messages as each of the three different places you need in the app.  It should look something like this:

``` objc
myCustomAlertView *instructions = [myCustomAlertView alloc] initWithMessage:@"Play this game...."];
myCustomAlertView *gameOver = [myCustomAlertView alloc] initWithMessage:@"Game Over"];
```
