### ISSUE TITLE
Sprite Kit Introduction

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#117]
I was going to have a look into Sprite Kit tonight...are there some good starting places anyone could suggest with nice tutorials and updated materials?  I was told that Unity is the way to go, but it has a learning curve with it that could be a bit of a time sink off the start.

Also possibly some solid materials on Authentication with a Rails backend using Devise for signup/login? This particular issue is all over the map when it comes to best practices.

Thanks!

**Comment by bobby-digital-23** [comment]
If you want a zero to game tutorial the Ray Wenderlich ones are good. They go in depth into SpriteKit and if you follow the entire tutorial(s), you have a pretty cool  working game at the end (there are several types of games if I'm not mistaken).

The Apple tutorials are great. Searching for them on the Apple Dev site can sometimes be a pain. 

There are tons of YouTube tutorials and several books solely dedicated to learning SpriteKit. 

Let me know how in depth you want to go and I'll share relevant links/references. :)

**Comment by bobby-digital-23** [comment]
Sorry, didn't see your entire post. 

They're all going  have a learning curve.

If you're looking to support multiple platforms - Unity is a decent choice but it does have licensing fees. 

You might find this of interest:
http://www.spritebuilder.com/about

**Comment by johnnypaper** [comment]
So taken from the RW site, it appears that Cocos2D-X may be a good place to start so that you aren't locked in to iOS.  Thanks...I'll have a look around.
![screen shot 2015-02-08 at 8 00 19 pm](https://cloud.githubusercontent.com/assets/6334967/6100021/bd269312-afcc-11e4-89f3-efc8422ae619.png)

**Comment by bobby-digital-23** [comment]
No prob. I did a fairly large project in Cocos2D and I enjoyed working with it. I found the Wenderlich tutorials helpful at that time. 

Spritebuilder is composed of maintainers from the various versions of CocosXX and another framework named Chipmunk. It's brand new and you can supposedly create both iOS and Andoid games with it (using XCode) but I've never tried it...

Good luck! :)

**Comment by johnnypaper** [comment]
Now I'm thinking Unity or Unreal (https://www.unrealengine.com/faq) which are C# and C++, respectively.  I have no idea.  I suppose I'm just going to have to pick one and roll on with it.  Thanks though for the nice tips.

**Comment by JRam13** [comment]
What is it that you are looking to do? 

Shameless plug:
https://itunes.apple.com/us/app/mathblast-pro/id738465780?ls=1&mt=8

I used Cocos2d for that game. However, I would advice against using cocos2d for ios, since I don't even think it's being supported anymore.

**Comment by johnnypaper** [comment]
Well...the thing is I don't know what I'm looking to do.  I just want to start and see what idea develops.  After checking out the Unity store http://unity3d.com/unity and the fact there is a free version with an IDE looks interesting.  I think I'm sold.  Unity it is.

**Comment by johnnypaper** [comment]
@JRam13 that's a nice looking game...very nice work.  How long did that take to develop if you don't mind me asking?  And how did you handle the artwork?  Or is that artwork mainly just a customized landscape layout?

**Comment by JRam13** [comment]
That was my final project for advanced iOS. Probably took me about a month or so to polish it and release it to the app store. 

The artwork is a combination of royalty free assets/wallpapers/icons. I'm also very handy using photoshop though.  

Ive also been working on this game using spritekit:
http://www.jrwebpro.com/spaceshooter/

That one, however, is a work in progress.

**Comment by johnnypaper** [comment]
Galaga Redux!  Man that was my favorite game in the arcade as a kid.  Still best stand-up true arcade game of all time. Then in the late 80s early 90s, Leisure Suit Larry came along.

Nice work @JRam13 ... I think that has some legs once it's all said and done.  The only thing that was  bit puzzling is how you die in the game...It seems like you could run into all of the enemies to kill them and the side fighter planes don't get destroyed.

**Comment by xiaoyifan** [comment]
I've been thinking of creating a game on iOS as final project, too. So which one U guys think might be better? Sprite Kit, or other 3rd party tool?  I've checked demo videos from SpriteBuilder, and it seems easier t handle. U can create basic behaviors of Sprites, and export to Xcode.

**Comment by tabinks** [comment]
Bring this up tonight in class.  We will be talking about final projects.
