### ISSUE TITLE
Final Project Proposal Submissions

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#121]
I've created a form to upload your project proposals here: http://goo.gl/RJBcTd

Please make sure your project includes the following information:
- Full Name (as registered with the University)
- Github Username
- Email address
- One paragraph summary of your app and its functionality
- Embedded image of your apps interface (it does not need to be very fancy).  Hand drawn sketches are fine.

The file should be converted to .pdf and be named in the following format: _github_username_-final-project-proposal.pdf.  The proposals are due this **Sunday, February 15th at 11:59PM**.  I will look at them on a rolling basis, so the earlier you get it in, the earlier you will get it back.

**Comment by bdeleon** [comment]
I've tried uploading my proposal and when I click upload, the message doesn't change from "uploading.."

I'm not sure if there's supposed to be another message indicating a completion. If not, I apologize for the 3 submissions.

**Comment by myu5** [comment]
Same issue here. The message keep saying uploading.... I am not sure if I successfully submitted the file or not.

**Comment by tabinks** [comment]
I'll check on them.  I was trying to use Google Drive to store them...we'll see if that worked.

**Comment by jhergott** [comment]
The "uploading..." issue happened to me too

**Comment by tabinks** [comment]
If you're having problems with the form, email me the proposal.
