### ISSUE TITLE
UAC Internship Link (Deadline is February 12th)

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#122]
Here is the link to the UAC internship.  The deadline is February 12th if you are interested: https://appchallenge.uchicago.edu/content/deadline-february-12-apply-app-programming-internship-mobile-and-web

**Comment by qualiahealth** [comment]
Joe and Andrew FTW!

**Comment by jiamaozheng** [comment]
submitted, thanks.
