### ISSUE TITLE
Office Hours - Thursday @ 4pm

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#123]
See you all at Crerar

**Comment by psajja** [comment]
Till what time will you be there ?

**Comment by bobby-digital-23** [comment]
What time could you be there?

I'm typically at office hours on Thursday from 4pm until approximately 6:30pm but officially it's supposed to be from 4-5pm. 😉

I do have plans for tonight so I'd appreciate it if you could arrive on the earlier side. Jonny and Julie typically have office hours tomorrow evening also btw.

**Comment by bobby-digital-23** [comment]
Any other takers today? I know it's a busy week due to midterms. Best of luck to you all. 😊

**Comment by psajja** [comment]
Never mind. Thanks bobby!! I don't think I will be able to make it today.
