### ISSUE TITLE
Need a clarification for proposal due time.

### ISSUE THREAD

**Issue by haouc** [uchicago-mobi/2015-Winter-Forum#127]
I saw the announcement said the final project proposal will be due at 11:59PM on Sunday, Feb. 16. Since Sunday is Feb. 15, I assume that you mean Sunday, Feb. 15? Please confirm this. Thanks.

**Comment by tabinks** [comment]
Yes, I meant the 15th.  I want them before class so I can have the chance to talk to anyone who has questions about it.

## Due Sunday, February 15th at 11:59 PM
