### ISSUE TITLE
Question about appearance of UIWebView

### ISSUE THREAD

**Issue by xctom** [uchicago-mobi/2015-Winter-Forum#128]
When I started the simulator, I found there was a black area on the bottom of UIWebView.
Does any body know how to get rid of it?
![image](https://cloud.githubusercontent.com/assets/4891624/6178517/44f71806-b2d5-11e4-9782-660742387ba0.png)

**Comment by tabinks** [comment]
Maybe you have the backgroundColor property set to black...  

Take a bigger screen shot and repost it.

**Comment by xctom** [comment]
![image](https://cloud.githubusercontent.com/assets/4891624/6183424/add1f496-b31a-11e4-9a61-53e4f70beaed.png)
Here is the bigger screen shot

**Comment by xctom** [comment]
It will disappear when the webView load content

**Comment by xctom** [comment]
And I find that it is in the UIWebView.
