### ISSUE TITLE
Does Anyone Need Office Hours Tonight?

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#13]
Would anyone plan on coming to office hours if they are offered tonight at 6:30?  
If so, please respond here by 4:00pm. 

Thanks.

**Comment by mallick1** [comment]
yes

**Comment by tabinks** [comment]
Office hours will be tonight at 6:30 in Young 306 (the computer lab).  Jonny, Julie or both will be there.

**Comment by mallick1** [comment]
i might not be able to make it ...any hours available during the weekend Sat/Sun or Mon?
