### ISSUE TITLE
Deleting Favorites

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#133]
So, I implemented this method in the FavoritesVC...

(void)tableView:(UITableView *)tableView commitEditingStyle:(UITableViewCellEditingStyle)editingStyle forRowAtIndexPath:(NSIndexPath *)indexPath

This allows for swipe deleting of the articles and deletion from NSUserDefaults...Is this acceptable?

I'm not really even sure of how to get the menu for all of the red negative sign buttons...and I somewhat like this one better anyway.  Seems like the edit on the bottom toolbar (which won't stick to the bottom in a fixed manner for me) is somewhat of an eyesore and the swipe delete seems to be the goto functionality on most apps these days anyway.

So, is this OK for the delete?

**Comment by tabinks** [comment]
You can put a table in editing mode by setting the editing property to YES.  This will show the editing controls.  Set to NO to hide them.

**Comment by narvemp** [comment]
I can't seem to move the toolbar (with the edit button) in the popover to bottom of the popover.  It seems stuck to right below the cells and I don't have the option of moving it or setting constraints.

**Comment by xiaoyifan** [comment]
I got the same issue. U can embed the bookmarkVC in a Navigation controller. then U can add the toolbar bar

**Comment by narvemp** [comment]
Thanks

**Comment by johnnypaper** [comment]
This doesn't work for me.  I had tried the embedding in nav controller 5 times before.  None of them work.  Super (and that's putting it nicely) frustrated with this assignment.
