### ISSUE TITLE
Issue with updating NSUserDefaults

### ISSUE THREAD

**Issue by hwealnegn** [uchicago-mobi/2015-Winter-Forum#134]
In order to update the favorited articles list saved in NSUserDefaults, I wanted to create a copy of the existing array (if it exists), add the new article to the array, and save the updated array back to NSUserDefaults. However, my app crashes when I click on my "Favorite This Article" button. The latest error that I'm getting in my NSLog tells me that I'm calling an array method on a string, but I'm not sure why (I think it's occurring when I try to copy the object from the NSUserDefaults?). I was wondering if someone could look over my code to check if I'm on the right track. This is what I currently have:

```
if ([defaults objectForKey:@"title"] != nil) {
    NSArray *copyArray = [defaults objectForKey:@"title"]; // create copy of existing array
    NSMutableArray *tempArray = [[NSMutableArray alloc] initWithArray:copyArray]; // create temp mutable array

    // check if selected article is already in array
    for (NSString *article in tempArray){
        if (article == self.detailItem[@"title"]) { // article already saved
            break;
        }
        // if article is not found
        [tempArray addObject:self.detailItem[@"title"]]; // add new article
        [defaults setObject:tempArray forKey:@"title"]; // save updated array to defaults
    }
} else {
    [defaults setObject:self.detailItem[@"title"] forKey:@"title"]; // initialize with first input
}

[defaults synchronize];
```

**Comment by tabinks** [comment]
Can you post the error log statement?

**Comment by tabinks** [comment]
A quick look makes me think this would return the "title" as a `NSString`, not an `NSArray`.  You are then treating it as an array in the next line:

``` objc
if ([defaults objectForKey:@"title"] != nil) { 
NSArray *copyArray = [defaults objectForKey:@"title"]; // create copy of existing array
```

**Comment by tabinks** [comment]
``` objc
NSLog(@"NSUserDefaults: %@", [[NSUserDefaults standardUserDefaults] dictionaryRepresentation]);
```

Will log user defaults to console.

**Comment by hwealnegn** [comment]
I modified the way that I copy the existing object into the temporary array, and it seems to work now! Instead of initializing a 'copyArray' with the object, I just add the object directly to the temporary mutable array.

`NSMutableArray *tempArray = [[NSMutableArray alloc] init]; // create temp mutable array`
`[tempArray addObject:[defaults objectForKey:@"title"]]; // add existing objects to array`

Thanks for your help!

**Comment by hwealnegn** [comment]
I thought my solution worked, but I realized that it was actually nesting each newly favorited object in the old object, and I've been struggling to resolve this.

Regarding my original issue, I think that the NSObject was being interpreted as an NSString since only one article had been saved to the NSUserDefaults. I tried ensuring that an array was being saved to NSUserDefaults by first doing the following to initialize the object:

```
    NSMutableArray *tempArray = [[NSMutableArray alloc] init]; // create temp mutable array
    [tempArray addObject:self.detailItem[@"title"]]; // add existing objects to array
    [defaults setObject:tempArray forKey:@"title"]; // initialize with first input
```

And subsequently, if the object "title" already existed in NSUserDefaults, assuming that the object was an array, I could use the following:

`NSMutableArray *tempArray = [[NSMutableArray alloc] initWithArray:[defaults objectForKey:@"title"]];`

However, now I'm getting the error:

`'*** Collection <__NSArrayM: 0x7fb7626c7aa0> was mutated while being enumerated.'`

The complete version of code that gives me the above error:

```
    if ([defaults objectForKey:@"title"] != nil) {
    NSMutableArray *tempArray = [[NSMutableArray alloc] initWithArray:[defaults objectForKey:@"title"]]; // create temp mutable array

    // check if selected article is already in array
    for (NSString *article in tempArray){
        if (article == self.detailItem[@"title"]) { // article already saved
            break;
        }
        // if article is not found
        [tempArray addObject:self.detailItem[@"title"]]; // add new article
        [defaults setObject:tempArray forKey:@"title"]; // save updated array to defaults
    }
} else {
    NSMutableArray *tempArray = [[NSMutableArray alloc] init]; // create temp mutable array
    [tempArray addObject:self.detailItem[@"title"]]; // add existing objects to array
    [defaults setObject:tempArray forKey:@"title"]; // initialize with first input
}
```
