### ISSUE TITLE
Office Hours - Monday @ 3:30 Crerar

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#137]
Please let me know if you will attend.

If needed, I will do my best to arrive earlier and post an update regarding the time here.

As always, posting questions ahead of time is helpful.

**Comment by johnnypaper** [comment]
I will be there.

**Comment by mceruzzi-denodo** [comment]
I'll almost certainly be there.

**Comment by mceruzzi-denodo** [comment]
"If needed, I will do my best to arrive earlier"

^If this is possible, I would very much appreciate it. I don't really have any specific question, but I just can't make sense of how to get the networking to work and it's preventing me from getting much of anything done.

Edit: Networking success!!! kinda...

**Comment by bobby-digital-23** [comment]
Happy to hear that you were able to get it to work, kinda. :+1: 

I will try to get to Crerar at least one hour earlier today. I will post the updated time this afternoon.

Please continue to post questions to the forum.

**Comment by mceruzzi-denodo** [comment]
Heh, well at the moment I can't get my UIWebView to show anything. Even when I physically hardcode:

NSString *string = @"www.yahoo.com";
    NSURL *url= [NSURL URLWithString:string];
    [self.web loadRequest:[NSURLRequest requestWithURL:url]];

Into the detailViewController's viewDidLoad method. i set it's delegate as the detailViewController and created an IBOutlet. I'm at a loss. Any ideas?

**Comment by JRam13** [comment]
I'll be there around 4 to take any questions as as well.

**Comment by psajja** [comment]
I will be there

**Comment by bobby-digital-23** [comment]
I will be at Crerar an hour earlier - 2:30pm. 

See you all soon. :)
