### ISSUE TITLE
Dismissing UIPopoverPresentationController

### ISSUE THREAD

**Issue by psajja** [uchicago-mobi/2015-Winter-Forum#138]
How do I dismiss the UIPopoverPresentationController from the DetailViewController. I have implemented the 

@protocol BookmarkToWebViewDelegate <NSObject>
- (void)bookmark:(id)sender sendsURL:(NSURL*)url;
  @end

I m trying to dismiss the pop over controller in the method (void)bookmark:(id)sender sendsURL:(NSURL*)url;. I have a handle on both bookmarkviewcontroller and the popoverpresenationcontroller. But I am not sure on what method to call on these to dismiss the pop over ? Stackoverflow has some pointers to dismissing the popover controller but I believe things have changes in ios 8.

**Comment by tabinks** [comment]
You have to dismiss it just like any normal view controller.  

```
[self.presentingViewController dismissViewControllerAnimated:YES completion:nil];
```

**Comment by psajja** [comment]
Thank you. That was straight forward. I have no idea what I was trying to do earlier.
