### ISSUE TITLE
Confusion about the gist

### ISSUE THREAD

**Issue by mceruzzi-denodo** [uchicago-mobi/2015-Winter-Forum#139]
I've looked over the gist several times, but can't seem to understand how it works. There is no url. Is the SharedNetworking class itself not supposed to reference the url we are pulling the data from?

**Comment by tabinks** [comment]
It's just an example of how to use a singleton and have a method that utilizes the blocks.  The implementation of the networking functionality is up to you (although it is pretty much done for you with the example).

To call it your would use the method signature:
`[SharedNetworking sharedSharedNetworking] yourMethod];`
