### ISSUE TITLE
Path to Repo for Assignment 1

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#14]
Everyone can find a private repo in the following format:
uchicagoid-MPCS51030-Winter-2015-Assignment-1

for assignment 1.  You and all the instructors have read/write permissions on it already.

Note:  I accidentally create a duplicate repo with the format uchicago--MPCS51030-Winter-2015-Assignment-1  (note the double "--").  Do not use this one, they will be deleted.  Use the one with the single dash.

**Comment by tabinks** [comment]
They are all under the organization uchicago-mobi.

**Comment by gitlaura** [comment]
When I try to go to https://github.com/uchicago-mobi/lrokita-MPCS51030-Winter-2015-Assignment-1 I get a 404 page. How should I find my private repo?

**Comment by nickmingyang** [comment]
I am not able to find my private repo either.

**Comment by tabinks** [comment]
If you can't find the repo please make sure that you're using the UChicago I'd filled out the form.  Some people put a numeric ID, which is not what I was looking for.  For these people I used the username in front of their @uChicago email.  You can go to the organization page and scroll down to see if you recognize yours in case it doesn't match what you think your ID wants.

If you still don't find your project please send me an email.

**Comment by tabinks** [comment]
Please check issue #19.  I have fixed the repos.

**Comment by myu5** [comment]
nickmingyang was my old github account name, I have changed it to myu5, which is same as my cNET ID.

Could you please use the new one and add me by that new github ID myu5?

Thank you!

On Jan 10, 2015, at 5:16 PM, tabinks <notifications@github.com<mailto:notifications@github.com>> wrote:


Please check issue #19<https://github.com/uchicago-mobi/2015-Winter-Forum/issues/19>. I have fixed the repos.
