### ISSUE TITLE
UIWebView not displaying anything

### ISSUE THREAD

**Issue by mceruzzi-denodo** [uchicago-mobi/2015-Winter-Forum#140]
I can't get my UIWebView to show anything. Even when I physically hardcode:

NSString *string = @"www.yahoo.com";
NSURL *url= [NSURL URLWithString:string];
[self.web loadRequest:[NSURLRequest requestWithURL:url]];

Into the detailViewController's viewDidLoad method. i set it's delegate as the detailViewController and created an IBOutlet. I'm at a loss. Any ideas?

**Comment by johnnypaper** [comment]
I copied and pasted this into a single view app with only a webview.  Here is your problem...

The code is fine, you need to change the string to @"http://www.yahoo.com"

It appears it won't work without the http://

**Comment by mceruzzi-denodo** [comment]
^Thanks!

**Comment by ceruzzi** [comment]
Ok, so I'm still unable to get the cell presses to load anything, even though I can confirm the method is being called.

As for testing things out in view did load, one thing I've noticed is that the following works:

NSURL *url= [NSURL URLWithString:@"http://www.google.com"];
    
    [self.web loadRequest:[NSURLRequest requestWithURL:url]];


Where as declaring an NSURL property and trying this does not work:

 _url= [NSURL URLWithString:@"http://www.google.com"];
    
    [self.web loadRequest:[NSURLRequest requestWithURL:_url]];


Nothing will load in the second instance. Anyone know why that would be?
