### ISSUE TITLE
Office Hours - Friday (NOT Thursday) @ 2-3:30pm Crerar

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#148]
Please note the change in day and time!

I will NOT be able to hold office hours tomorrow (Thursday) as usual. To make up for this I have shifted my office hours forward one day to Friday.

To repeat - my office hours will be held this FRIDAY (NOT on Thursday!) in Crerar from 2pm until at least 3:30pm.

Jonny typically holds his office hours on Friday evening. I will hold my following office hours next Monday, as usual, before class. As always, please post questions to the forum!

Please let me know if you will attend on Friday. I would appreciate it if you could tell fellow classmates who are (still!) not using these GitHub forums about the day & time change.

Thank you, stay warm, and see you on FRIDAY. :)

**Comment by bobby-digital-23** [comment]
One more thing:
I am reasonably flexible in regards to how much time I can spend on Friday. Several of you have asked for tutoring on specific topics so if you need extra help please contact me ASAP and we will try to arrange time before or after the official office hours. FYI, I do have plans that evening so the earlier the better.

**Comment by qualiahealth** [comment]
I will also hold office hours on Friday, unsure about the time though. Last week I stayed there for about 5 hours...

**Comment by JRam13** [comment]
I will also hold office hours on Friday, unsure about the time though. Last week I stayed there for about 5 hours...

**Comment by bobby-digital-23** [comment]
Email:
bobkanuri@gmail.com
