### ISSUE TITLE
Help needed! Unable to Run App in Simulator

### ISSUE THREAD

**Issue by mallick1** [uchicago-mobi/2015-Winter-Forum#15]
When i try to run the hello world app, i get the following error:

An error was encountered while running (Domain = DTiPhoneSimulatorErrorDomain, Code = 2)

I tried resetting content & setting for the OS Simulator and it did not fix the problem.  
How do i fix this problem?
Thanks!

**Comment by mallick1** [comment]
i found a solution here:
http://stackoverflow.com/questions/24033417/unable-to-run-app-in-simulator-xcode-beta-6-ios-8

basically deleted the existing simulator for 5s and added them back.

**Comment by tabinks** [comment]
Thanks for sharing.  I'll leave this up here in case anyone else has same problem.

**Comment by mallick1** [comment]
you are welcome! wasted an hour to figure this out:-)
