### ISSUE TITLE
viewWillUnload and viewDidUnload are Deprecated after iOS 6

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Winter-Forum#151]
Lecture 7 discussed the necessary to remove NSNotificationCenter. I find that viewWillUnload and viewDidUnload are deprecated after iOS 6. Where and how are NSNotificationCenter removed?

![screen shot 2015-02-19 at 9 48 00 pm](https://cloud.githubusercontent.com/assets/4560331/6280763/06b14056-b881-11e4-9d1e-80691b910a18.png)

**Comment by bobby-digital-23** [comment]
Did you try their replacements - viewWillDisappear or viewDidDisappear?

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/index.html#//apple_ref/occ/instm/UIViewController/viewWillDisappear:

**Comment by yiqin** [comment]
If we do removing NSNotification in viewWillDisappear or viewDidDisappear, we need to add NSNotification in viewWillAppear or viewDidAppear. But sometimes, we still want to use NSNotification to broadcast some view controllers that are not in Appear state.

**Comment by bobby-digital-23** [comment]
I'm not sure that I understand your original question. How does the deprecation of viewWillUnload and viewDidUnload change what you are trying to achieve? Whenever you register for a notification (addObserver) you must also unregister (removeObserver) at some point. You are not limited to solely using viewWillAppear or viewDidAppear and the complementary methods - viewWillDisappear and ViewDidDisappear - to accomplish this. 

Could you please post some code?

Please let me know if any if these help you:

http://stackoverflow.com/questions/15600079/sending-data-between-vcs-using-nsnotificationcenter

http://stackoverflow.com/questions/14801889/applicationdidfinishlaunchingwithoptions-firing-notification-before-destinatio

http://stablekernel.com/blog/uiviewcontroller-best-practices-viewwillappear-or-viewdidload/

https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/RespondingtoDisplay-Notifications/RespondingtoDisplay-Notifications.html#//apple_ref/doc/uid/TP40007457-CH12

https://developer.apple.com/library/ios/featuredarticles/ViewControllerPGforiPhoneOS/ManagingDataFlowBetweenViewControllers/ManagingDataFlowBetweenViewControllers.html#//apple_ref/doc/uid/TP40007457-CH8-SW1

**Comment by tabinks** [comment]
@yiqin You are correct that they deprecated.  I should have updated the slide.  You could explore putting them in `viewDidDisappear` instead.  This all depends on your implementation details.  You can remove observers at any time from anywhere in the code.  There is nothing special about calling it in `viewDidAppear/Disappear`
