### ISSUE TITLE
Cells not resizing

### ISSUE THREAD

**Issue by thomkel** [uchicago-mobi/2015-Winter-Forum#155]
I'm not sure what I'm doing wrong, but I can't get the cells of the Master View to resize.

I added the following to viewDidLoad:

 self.tableView.estimatedRowHeight = 150.0;
    self.tableView.rowHeight = UITableViewAutomaticDimension;

And this is the relevant code in cellForRowAtIndexPath

```
UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"newsCell" forIndexPath:indexPath];

UILabel *titleLabel = (UILabel*)[cell viewWithTag:100];
UILabel *dateLabel = (UILabel*)[cell viewWithTag:101];
UILabel *contentLabel = (UILabel*)[cell viewWithTag:102];
```

// set label text values

```
[cell setNeedsDisplay];
[cell layoutIfNeeded];

return cell;
```

I'm sure I'm missing something obvious here.

**Comment by tabinks** [comment]
Remember to set the constraints on the cell using autolayout.  Also, set the UILabel number of lines to be 0 (unlimited lines).  The default is 1 line.

**Comment by emondai** [comment]
I was able to get it working using this guide: http://www.raywenderlich.com/73602/dynamic-table-view-cell-height-auto-layout
