### ISSUE TITLE
for star position

### ISSUE THREAD

**Issue by cheng-wu** [uchicago-mobi/2015-Winter-Forum#158]
In the requirement, only requires us to let the star to be seen all the time. So I put it to the right corner, but the in the slides, instructor put it to left, and when master view cover it, the star move to right corner. 

I am just not sure what do you exactly expect us to do on this one?

**Comment by mattmeier** [comment]
I'm wondering the same actually!

**Comment by tabinks** [comment]
On iphone put it on the left, on iPad put it on the right.  This is an exercise for you to understand adaptive layouts.
