### ISSUE TITLE
Favorites and NSUserDefaults

### ISSUE THREAD

**Issue by mattmeier** [uchicago-mobi/2015-Winter-Forum#159]
In our assignment it says "Persist the user's favorite articles to disk by implementing NSCoding protocols on a custom data class." Does that mean we scratch the NSUserDefaults implementation of Favorites and just have the new NSCoding/NSData one or do we have them in parallel/keep the NSUserDefaults Favorites objects?

**Comment by tabinks** [comment]
You only need to keep the new custom favorites.  You do not need to keep them in `NSUserDefaults` anymore.
