### ISSUE TITLE
launchscreen.xib does not show up

### ISSUE THREAD

**Issue by xctom** [uchicago-mobi/2015-Winter-Forum#16]
I works before but it does not show up now. I have make sure my setting is right. And here is the screen shot of my setting:
![image](https://cloud.githubusercontent.com/assets/4891624/5693488/40a844ec-98e4-11e4-8521-743d3c2f02b8.png)
Now the launch screen is just black in the simulator( I even try to create another launchscreen and it does not work either). It is wired because I don't remember I have done some change to the launchscreen.

**Comment by tabinks** [comment]
Are you using a custom image for the launch screen or a storyboard based launch screen?

**Comment by xctom** [comment]
No, I only use custom image for app Icons.
