### ISSUE TITLE
About splash screen

### ISSUE THREAD

**Issue by xiaoyifan** [uchicago-mobi/2015-Winter-Forum#162]
Hi, I'm still wondering about the Splash screen effect. What's the specification of this? I've checked the tips in issue #149, the code just created a VC in green and present the VC in detailVC. However, the requirement says: Once the data is loaded, it should fade away and present the MasterViewController.....So the splash screen is supposed to cover MasterView, or DetailView, or even both of them?

**Comment by tabinks** [comment]
Yes.  The splash screen should cover the screen.  The green screen was an example of how to present it, you will need to figure out how to remove it accordingly.

**Comment by xiaoyifan** [comment]
Sure, no problem. I just implemented the effect in DetailViewController, it works fine but the effect only appears in detail view in iPhone. Then I moved it to MasterViewController. It works in iPad, but comes up with warning: Attempt to present <UIViewController: 0x7fb968e70de0> on <MasterViewController: 0x7fb968c87520> whose view is not in the window hierarchy!...............So is there any better way to do that?

**Comment by xiaoyifan** [comment]
What if I just initialize a view, not ViewController to implement this?

**Comment by tabinks** [comment]
Do it however you want, as long as it accomplishes the stated functionality.

**Comment by JRam13** [comment]
> What if I just initialize a view, not ViewController to implement this?

Great question and one that should have been asked long ago.

**Comment by xiaoyifan** [comment]
Thanks, it's done. Implementing this as UIView is better than ViewController.
