### ISSUE TITLE
Centering Toolbar Text in iPhone Portrait Mode

### ISSUE THREAD

**Issue by alextsu** [uchicago-mobi/2015-Winter-Forum#163]
Hey gang,

I'm having trouble centering the text of my toolbar specifically in iPhone Portrait mode. I currently use two flexible spaces on the left and right of the text, which works in every other mode. However, this is what I see when I use an iPhone in portrait mode (look at the bottom left of the screenshot):

How do you guys solve this?

![screen shot 2015-02-22 at 9 40 45 pm](https://cloud.githubusercontent.com/assets/6432040/6322530/ccb7f716-badb-11e4-96b8-152edf12ae29.png)

**Comment by tabinks** [comment]
That is interesting.  Check to make sure you didn't accidentally set a constraint in one of the layout class.
