### ISSUE TITLE
Location for NSCoder ?

### ISSUE THREAD

**Issue by psajja** [uchicago-mobi/2015-Winter-Forum#165]
I would like to know the location of the .plist file for the NSCoder ? I remember prof. showing us the location of the files associated with the simulator. I forget the location. Thanks.

**Comment by JRam13** [comment]
I would also like to have this clarified. If you go the route where you're writing to the Document's directory (as shown below), I don't think you have access to that plist. I also don't think it's possible to write to your bundles directory either. My hunch is you won't be able to see that plist. I think what you saw in class was a pre-made plist file for demonstration purposes. 

``` objC
NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);

NSString *documentsDirectory = [paths objectAtIndex:0];
NSString *appFile = [documentsDirectory stringByAppendingPathComponent:FAVORITE_LIST_NAME];

[NSKeyedArchiver archiveRootObject:yourFavoriteList toFile:appFile];
.
..
...
```

**Comment by psajja** [comment]
Thanks Jonny.
