### ISSUE TITLE
My iOS app - LeetCoding launched on App Store

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Winter-Forum#169]
![leetcoding-58](https://cloud.githubusercontent.com/assets/4560331/6358587/534f38c8-bc32-11e4-8f6d-e5fc3e303c4a.png)
Hi everyone. My latest iOS app - LeetCoding launched on App Store.

LeetCoding lets you review coding interview questions in your phone. Just review. Use your spare time to review these questions. No coding until you know how to solve the problem. LeetCoding is definitely the app you want to use at the first step of your interview preparation.

 https://itunes.apple.com/us/app/leetcoding/id963066061?mt=8

![screen322x572-8](https://cloud.githubusercontent.com/assets/4560331/6358572/3a5ab9c8-bc32-11e4-9b18-2dc5f20d376f.jpeg)
![screen322x572-9](https://cloud.githubusercontent.com/assets/4560331/6358568/37a4fa0e-bc32-11e4-93bb-eeeac9af3959.jpeg)

**Comment by qualiahealth** [comment]
Great job! Feels like I'm back in Algorithms with Brady... 

![](http://assets.diylol.com/hfs/e14/eae/85c/resized/engineering-professor-meme-generator-spent-a-year-developing-new-algorithm-asks-you-to-do-it-in-a-weekend-1051a6.jpg)

**Comment by JRam13** [comment]
Great job! Feels like I'm back in Algorithms with Brady... 

![](http://assets.diylol.com/hfs/e14/eae/85c/resized/engineering-professor-meme-generator-spent-a-year-developing-new-algorithm-asks-you-to-do-it-in-a-weekend-1051a6.jpg)

**Comment by xctom** [comment]
Great job! Feels like I'm back in Algorithms with Brady...
https://camo.githubusercontent.com/1bd295de1f7969abba21ccccfb80ae2048fd2eb1/687474703a2f2f6173736574732e6469796c6f6c2e636f6d2f6866732f6531342f6561652f3835632f726573697a65642f656e67696e656572696e672d70726f666573736f722d6d656d652d67656e657261746f722d7370656e742d612d796561722d646576656c6f70696e672d6e65772d616c676f726974686d2d61736b732d796f752d746f2d646f2d69742d696e2d612d7765656b656e642d3130353161362e6a7067

**Comment by johnnypaper** [comment]
Very nice work!...Is that your final project?

**Comment by xctom** [comment]
Great job! Feels like I'm back in Algorithms with Brady...
![687474703a2f2f6173736574732e6469796c6f6c2e636f6d2f6866732f6531342f6561652f3835632f726573697a65642f656e67696e656572696e672d70726f666573736f722d6d656d652d67656e657261746f722d7370656e742d612d796561722d646576656c6f70696e672d6e65772d616c676f726](https://cloud.githubusercontent.com/assets/4891624/6358813/ffbf4e3a-bc33-11e4-9ad2-873c1d5ec549.jpeg)

**Comment by johnnypaper** [comment]
@xctom ... And how does that make you feel?

**Comment by yiqin** [comment]
@johnnypaper It was developed from one of our homework - build an app for GitHub. I reused most part of the code. I planed. But I found that the final project require a lot of staff....  The app maybe not good enough to be a final project.

**Comment by JRam13** [comment]
Missed an opportunity to name it 1337Coding!

**Comment by yiqin** [comment]
@JRam13 Thanks. That's the most difficult course I have even took.

**Comment by yiqin** [comment]
@JRam13  What does 1337 mean?

**Comment by JRam13** [comment]
leet in nerdspeak.

**Comment by yiqin** [comment]
@JRam13 I like this name. Let me change the name now.

**Comment by bobby-digital-23** [comment]
http://en.m.wikipedia.org/wiki/Leet

Congrats!!!! :)

**Comment by johnnypaper** [comment]
*fun with binary --- it always warms the soul

**Comment by narvemp** [comment]
cool app!  just out of curiosity, where did you find the problems?

**Comment by JRam13** [comment]
[![](http://img.youtube.com/vi/faCvYS1nsHg/0.jpg)](http://www.youtube.com/watch?v=faCvYS1nsHg)

**Comment by yiqin** [comment]
@narvemp I used Kimono Lab https://www.kimonolabs.com/ to scratch questions from different websites.  Then put all data to the cloud database https://parse.com/customers   Parse.com is super easy to use. If you want to a backend for your final project, I can help you to setup in 10 mins.

**Comment by johnnypaper** [comment]
@yiqin seems only problem is the exponential scale...I looked at parse and they nail you if you're over the 30 req/s

Did you throttle that in some sort of way... like hit it in a loop to see what occurs after you hit the mark?

**Comment by JRam13** [comment]
@johnnypaper we use Parse.com for Qualia, we have over 1Million requests a month (scripts that sync with Fitbit/Withings/iHealth data). We don't reach nowhere near 30 req/s.

If you're getting 30req/sec, you can afford the heavy price tag.

**Comment by JRam13** [comment]
@johnnypaper Ok I lied a bit, and req/sec is very different than total requests. However, my conclusion still stands, 30 req/sec is pretty good for a free tier. Also, there are ways you can control this, it all depends how you implement requests and data transfers in your code.

**Comment by johnnypaper** [comment]
I was just doing some math...and I'm not very good with it...but I don't believe 30/s is outside the realm.  In totality perfectly synchronized in a month that would be 77.76M...and yeah that seems like plenty.  However, clustering is the real issue.  And I bet you're gonna have to roll out that checkbook pretty soon.  Question is, what occurs with the app ONCE that is hit.  Timeout? Halt of API key until you put in a credit card?  timeout for a second ....who cares.  Halt until pay or auto pay...mmmm.  That's not good news.

**Comment by yiqin** [comment]
@johnnypaper It returns an error that states "something wrong  bararaba ". I think you don't need to worry about it. Few apps can reach 30 req/sec.

**Comment by JRam13** [comment]
@johnnypaper You don't even start thinking about req/sec with under 10,000 users. If you have more than 10,000 users, you should have enough revenue to cover your backend costs. On top of that, the way you save data in parse is by calling `saveInBackgroundWithCompletion:` which returns a success block if the transfer was successful (or an error). If by some chance there's an error, you can handle this scenario in code. 

My point is, this shouldn't discourage you from using something like Parse.com. I know you either love it or hate it, but it truly is one of the simplest backend services I've used.

**Comment by bobby-digital-23** [comment]
Downloaded your app and gave it 5 stars. Great job!

**Comment by johnnypaper** [comment]
All interesting points.  And that seems nice to handle any errors in that manner.  I'll have to give it another look. Thanks for the pointers.  And nice job once again @yiqin!

**Comment by yiqin** [comment]
@bobby-digital-23  @johnnypaper  Thanks.

**Comment by tabinks** [comment]
Congrats.  It's always a big deal to get anything in the store.  I agree about Parse, it is a great way to get up and running.  Once you are dealing with 1M+ requests/month, you can either afford to pay them or get someone to develop a cheaper backend.  Also, don't forget about CloudKit...if its on iOS, you get all this for free.
