### ISSUE TITLE
Office Hours - WEDNESDAY @ 2pm Crerar

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#170]
Please note the day and time change. I will not be able to attend on Thursday, sorry.

If you have specific questions about your final project, posting code prior to office hours and contacting me would both be appreciated. :)

**Comment by tabinks** [comment]
Since Bobby is having office hours today, I will plan on having them tomorrow (Thursday) afternoon.  I will post the exact time/location as a new issue later today, but most likely it will be around 12:00pm.

**Comment by johnnypaper** [comment]
On my way.

**Comment by bobby-digital-23** [comment]
In the back of Crerar with Jerry

**Comment by bobby-digital-23** [comment]
Office hours today officially finished. Please remember that our professor will be holding office hours tomorrow. Look for his announcement.

It was nice to see some of you start your final projects well ahead of the due date. They're looking great! Keep up the good work.  :)
