### ISSUE TITLE
App Crashing on Phone but not on Sim

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#173]
I've got an issue where the phone by itself is crashing. However, the phone plugged into xCode things are fine.  Any ideas.

I have no clue about this NSZombie... debug that people are talking about on SO.

This is super frustrating not really having a clue as to how to debug all of this.

Any help would be greatly appreciated.

**Comment by jiamaozheng** [comment]
same issue here.

**Comment by johnnypaper** [comment]
What is it surrounding in your app do you think?...I can spot the place where it crashed on my phone, but since xCode succeeds I can't reproduce the error and make it crash when plugged in to xCode using the phone.  Does your crash have anything to do with things being added to or removed from NSUserDefaults or altering NSUserDefaults in any way?  Are you using any network connections?

**Comment by jiamaozheng** [comment]
I am really not sure. Similar to yours, my app work on Simulator all the time, but it crashed on the iPhone sometime for unknown reasons.

**Comment by johnnypaper** [comment]
_Big Post-It Note_:  This could potentially save you time enough to drive to California and back on a horse...---> **_DO NOT_** save an NSMutableArray to NSUserDefaults.  Save an NSArray or use another method.

This will work on the Simulator in fine fashion...then it will crash your mind :goberserk: trying to figure out the problem on the phone.  Another iOS mind bender courtesy of iOS8.  For anyone using a NSArray off the bat...consider yourself very lucky.  This hurt my soul trying to figure it out.

**Comment by jiamaozheng** [comment]
I have tried different devices and it may be related to memory issues. It crashed in my old iPhone4s and iPad, but worked well in my iPhone6plus.
