### ISSUE TITLE
Check List for final project

### ISSUE THREAD

**Issue by psajja** [uchicago-mobi/2015-Winter-Forum#174]
Hi - I thought Prof. mentioned he would upload a check list for the final project. I wasn't sure if he was just referring to the slides or a separate sheet of paper he would upload .

**Comment by tabinks** [comment]
I will be posting it tomorrow with the lecture slides.

**Comment by psajja** [comment]
Thank you

**Comment by thomkel** [comment]
Was the checklist posted? I didn't see if in the slides
