### ISSUE TITLE
about Navigation Controller

### ISSUE THREAD

**Issue by xiaoyifan** [uchicago-mobi/2015-Winter-Forum#175]
![screen shot 2015-02-27 at 9 04 06 pm](https://cloud.githubusercontent.com/assets/9085563/6424584/35ec32d8-bec4-11e4-8012-064f499c16bf.png)

As shown on the screen shot, I embed the detailViewController in the NavigationController, and the MainViewController on the left is not. What I want to achieve is when the user tap the tableViewcell on the mainViewController, it will segues to the detailVC. It's done. But how can I go back with tapping on the X button? I can't use unwind cuz mainVC is not embed in NavigationVC.

I tried to use dismissViewController, but it seems, if I go back to mainVC, I can segue to detailVC instantly. I guess that's because the allocation and deallocation of VC takes time. 

So any advice? 

Thanks

**Comment by tabinks** [comment]
You should embed master in the navigation controller.  Unless I'm missing something this is perfect example of using unwind segue.

**Comment by xiaoyifan** [comment]
Yep. I'm trying to get rid of the Navigation controller, cuz the customization on the NavigationBar is limited, so I wanna implement this without navigationController. I just used the dismiss method, it works. And I can do data saving in viewWillDisappear

**Comment by tabinks** [comment]
Don't forget, you can hide the navigation bar while still having the view controllers embedded in a navigation controller.  You could create the interface how ever you want and just call the normal navigation controller behaviors from those.  Just an option...

**Comment by xiaoyifan** [comment]
OH MY!!!I forgot this~~~I just implemented by pushing VC and dismiss it later. thank U so much!
