### ISSUE TITLE
Fontastic: Fonts as Icons

### ISSUE THREAD

**Issue by narvemp** [uchicago-mobi/2015-Winter-Forum#178]
Stumbled across this cool icon library.

From the website:
"The same mathematics you hated in high school is now creating vector icons that look good at any size. No longer export different sized .PNG versions of your icons for your responsive designs; let them resize automatically to your users screen, no matter how big or small."

http://fontastic.me

**Comment by tabinks** [comment]
Other good icon resources:
- icon8
- deviantart
- thenounproject

Also, don't forget Google image search.  In the advanced settings, you can filter by license to find `free to use` icons.  If you are using icons with attribution requirements, this is a good thing to tuck away on a `Settings.app` page.
