### ISSUE TITLE
Class Monday - Tutorial: Tic-Tac-Toe online multiplayer (using Parse.com)

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Winter-Forum#181]
Ok, I'll do it! Jeesh.

![](http://valeriecoffman.com/wp-content/uploads/2014/02/parse_all_the_data.jpg)

**Comment by xiaoyifan** [comment]
AWESOME!! CANT WAIT!

**Comment by JRam13** [comment]
I also heard...

![](http://cdn.meme.am/instances/500x/59508840.jpg)

**Comment by johnnypaper** [comment]
Is that a microphone?...Oh. Just a sword.

**Comment by JRam13** [comment]
Not just any sword! It's the 'Ice'.

> Ice was a Valyrian steel greatsword and an heirloom of House Stark. It was used both in war and on ceremonial occasions by the Lord of Winterfell.

Common man, everyone knows this!

**Comment by johnnypaper** [comment]
It still looks like a steel microphone (like a steel ceremonial microphone to be exact) at that angle.  Perhaps you've got some better shots from higher on a mountaintop where it really resembles a sword.  Then again maybe the Lord of Winterfell, the artist formerly known as the Lord of Springfell, is hosting a singing competition in that photo and whoever that may be is practicing with a sword.

**Comment by JRam13** [comment]
You mean like this

![](http://www.qualiahealth.com/misc/meme.png)
