### ISSUE TITLE
Office Hours - Thursday @ 3:30pm Crerar

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#184]
Please let me know if you might attend. See you there!

**Comment by xiaoyifan** [comment]
I'll be there~

**Comment by bobby-digital-23** [comment]
Might be several minutes late. Very close to campus on Lake Shore Drive but traffic is unusually bad. Radio just told me that "a car is on fire" on 31st St! 😳

See you soon.

**Comment by bobby-digital-23** [comment]
Found parking. See you in 5.

**Comment by bobby-digital-23** [comment]
Done for today. 

I will try my best to hold office hours again tomorrow. I will post a message with details later tonight.
