### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by thomkel** [uchicago-mobi/2015-Winter-Forum#186]
Maybe I missed it, but was the checklist posted with the lecture notes?

**Comment by tabinks** [comment]
Sorry about that.  Here is the link: https://ff8276a3d76177159b643022d4cc86d3f633fc86.googledrive.com/host/0B3XzcKIiWyccdlgtOW42N0xQZjQ/MPCS51030/2015-Winter/2015-Winter-FinalProjectRequirements.pdf

It's also available from the "Sessions" page on the website.

**Comment by thomkel** [comment]
Thank you!
