### ISSUE TITLE
Office Hours - Today (Friday) @ 3:30pm Crerar

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#188]

**Comment by JRam13** [comment]
Thanks for doing this, I won't be able to do tonight.

**Comment by bobby-digital-23** [comment]
No prob Jonny. Hope all is well with you. 😊

Students, nice to see so many of you put in such great  effort on your final projects. They're looking really nice - can't wait to see you all demo them in class! 👍
