### ISSUE TITLE
CSIL Mac lab selling old Mac Pros!!!!

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#189]
For those of you who are looking for a Mac and who don't mind if it's a tower, the CSIL in Crerar is selling their older Mac Pros for very cheap! Their cheapest model (with 8 cores) is selling for less than the cheapest new Mac Mini which does not even compare power wise although it is much tinier. Keep in mind that there are no warranties and that these machines have been used in the lab nonstop but since they are the older tower style, they're easy enough to open and fix should they ever break down...

Anyways, if you're interested, here's the link. Act fast as they are going quick! Alex figured out that the same models are selling for 4-6x the cost on eBay and Amazon!

http://bit.do/csil-resale2015

One last thing, I reserved several more machines than I intend to buy so if you're looking for one of the higher end 12 or 24 core models, let me know. 😊

**Comment by narvemp** [comment]
I'll buy 1-2 of the 24 core ones if you don't mind!

**Comment by jiamaozheng** [comment]
Good deal. I bought three of MacPro from the CSIL last year. So far so good, and still working well. But they are very heavy :)

**Comment by xiaoyifan** [comment]
Yeah, bobby told me this, and I reserved one. Looks a great deal
