### ISSUE TITLE
GitHub Repos: Take 3 (For Real This Time)

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#19]
I have recreated GitHub repos but instead of using your uchicago usernames, I have created them using your **GitHub username** as the prefix.  All repos are in the following format:

_github_username_-MPCS51030-Winter-2015-Assignment-1

For example my repos would be:

tabinks-MPCS51030-Winter-2015-Assignment-1

A couple notes about the repos:
* All the instructors have read/write access to the repos so you will not need to change or set permissions on them.
* These private repos will be yours for the duration of the course.  At the end of the quarter, they will be deleted.  I will notify you before this happens.
* We will grade the _master_ branch of the assignment, so make sure to merge it before the deadline.
* All assignments will be automatically pulled on the due date, this is what will be graded.

Sorry for the confusion with bitbucket/usernames.  GitHub provides a very nice solution once everything is set up properly.  If you have any questions, please post them here.

**Comment by tabinks** [comment]
The following github accounts were submitted in the form, but do not exist in github.  If one of them is yours, please email me:
* edai@uchicago.edu
* psajja@uchicago.edu
* nickmingyang

**Comment by myu5** [comment]
How can I find the private repo in github?

**Comment by xiaoyifan** [comment]
I can see the repo first, and it's gone now

**Comment by kaiyuand** [comment]
me too, it is gone....

**Comment by tabinks** [comment]
![image](https://cloud.githubusercontent.com/assets/93689/5693700/f0acccae-98ef-11e4-8a9c-bcf1fcbfd517.png)

I see it.

**Comment by tabinks** [comment]
All repos are under the organizatio uchicago-mobi at https://github.com/uchicago-mobi

**Comment by jhergott** [comment]
I originally saw my private repository after the first invitation to github.  I committed and pushed my assignment smoothly.  Now, after the second invitation, I can no longer see my repository... Not sure what happened here.

**Comment by kaiyuand** [comment]
I can't find it, I only have the forum and the mobi under the organization uchicago-mobi

**Comment by tabinks** [comment]
Can you all check again.  I see them and it looks like the permissions are fine (from what I can see).

**Comment by jhergott** [comment]
Yup, I see it again.  Thank you

**Comment by tabinks** [comment]
## Compared to this, iOS development is easy

**Comment by susanstevens** [comment]
I'm not seeing mine.  I went to https://github.com/uchicago-mobi and I'm logged in.  Am I missing something?

**Comment by bobby-digital-23** [comment]
You don't see it at this link?

https://github.com/orgs/uchicago-mobi/teams/susanstevens

**Comment by susanstevens** [comment]
Nope. I see "3 members, 0 repositories."  And when I click on the Repositories tab (next to Members), it says "This team does not give members access to specific repositories."

**Comment by bobby-digital-23** [comment]
You are correct Susan.
Looking into this now. Someone will let you know as soon as it is fixed.

And yes - iOS Dev is easier and way more fun than this!!!! ;)

**Comment by tabinks** [comment]
Susan.  Please try again.  I just updated settings for your team.

**Comment by susanstevens** [comment]
I see it now.  Thanks!

**Comment by johnnypaper** [comment]
I also do not see where my repo would be...or what username it would be.  My own repo that I use is johnnypaper... so I'm assuming there should be something available for bsaterfiel.

**Comment by tabinks** [comment]
@johnnypaper Did you fill out the Google Form?  I don't see your information on it.

**Comment by johnnypaper** [comment]
I did fill out the form and here is the confirmation email snapshot...

![screen shot 2015-01-10 at 8 55 42 pm](https://cloud.githubusercontent.com/assets/6334967/5694155/ae51cfe2-990a-11e4-9f98-5e1175423a36.png)

**Comment by tabinks** [comment]
There was a second form to fill out with you github information.  I just manually added it.  You should see your repo under the uchicago-mobi organization in a couple of minutes.

**Comment by johnnypaper** [comment]
ok, i see...I will check in a moment.  Thanks.

**Comment by tabinks** [comment]
https://github.com/uchicago-mobi/johnnypaper-MPCS51030-Winter-2015-Assignment-1

**Comment by johnnypaper** [comment]
I'm with it now.  Since this is a one-off on the first assignment, will this be the process each time?  Obviously you will have the usernames, but 8 different repos for each person over the course?

**Comment by tabinks** [comment]
Yes, there will be one repo for each assignment and one for the final project.  Each week, a repo will be created for the assignment.

**Comment by bobby-digital-23** [comment]
Please consider:

Repos as a private team on github are now free and plentiful for this course thanks to Dr Binkowski. GitHub used to offer this to universities but no longer does which is why we were initially going to use bitbucket. Since it seems like everybody is/was already using GitHub, our professor personally asked GitHub for an exception for this course and was granted one. It will be now be that much easier to merge your repos with the rest of your projects in github and show them to whoever you like. :)

The time that the professor and TAs will have each week to grade 40+ student assignments is exactly the opposite of plentiful - hence the separate repos and naming conventions. 

Hope this explains why the switch was made and why we're asking for separate repos for each assignment. ;)

**Comment by tomdumu** [comment]
I still cannot see my repo

**Comment by egbertc** [comment]
I am unable to see my repo as well. I've got the same situation as susanstevens from above.

**Comment by xiaomaogy** [comment]
I am unable to see my repo, I used  all of the option and none of them works
https://github.com/uchicago-mobi/yg79-MPCS51030-Winter-2015-Assignment-1
https://github.com/uchicago-mobi/xiaomaogy-MPCS51030-Winter-2015-Assignment-1
https://github.com/uchicago-mobi/yuangao-MPCS51030-Winter-2015-Assignment-1

**Comment by jvmakin** [comment]
Hey! I just made my github account, for some reason I missed the email telling us we had switched from bitbucket. Where can I find my repo?

**Comment by bdeleon** [comment]
I've been out of town for a few days so I was late to the game filling out the github form. When should I be able to access my private repo?

**Comment by tabinks** [comment]
@xiaomaogy Did you fill out the form?

**Comment by tabinks** [comment]
@egbertc Check for your repo.  I updated the settings on it.

**Comment by yiqin** [comment]
I don't see my repo neither...

**Comment by egbertc** [comment]
@tabinks I see it. Thanks!

**Comment by thomkel** [comment]
I also don't see my repo

**Comment by tabinks** [comment]
@yiqin  Check again.  I can see that its there.

**Comment by tabinks** [comment]
@thomkel Check again.  I updated settings.

**Comment by thomkel** [comment]
@tabinks I see it. Thank you!

**Comment by tabinks** [comment]
### If you do not see your repo in the organization, do not let that stop you from finishing the homework and having it ready to turn in.  This is just the way to submit the homework and should have no bearing on your ability to complete the assignment. ###

**Comment by tabinks** [comment]
@jvmakin @bdeleon I just created your repos.  Let me know if you don't see them.

**Comment by davidcl1** [comment]
Hi, I submitted the form this morning. Just wondering if you got my info.

**Comment by narvemp** [comment]
Can you create a repo for me as well?  Thanks

**Comment by jiamaozheng** [comment]
I still didn't see my repos. Would you please create one for me? Thank you,

**Comment by xiaomaogy** [comment]
Yes, I did. My netID is yg79

**Comment by ceruzzi** [comment]
Hi, I also cannot see my repo.

**Comment by ronmexico15** [comment]
I'm not finding my repo either. https://github.com/uchicago-mobi/ronmexico15-MPCS51030-Winter-2015-Assignment-1 is giving me a 404.

**Comment by tabinks** [comment]
@ronmexico15 You need to accept the invitation to the team before you can see the repo.  Check your inbox.

**Comment by tabinks** [comment]
@ceruzzi Repo should be there.

**Comment by tabinks** [comment]
@xiaomaogy You are not listed on the form.  Please fill it out again so I can add you to team.

**Comment by xiaomaogy** [comment]
@tabinks  I just resubmitted the form. Thank you!

**Comment by tabinks** [comment]
@narvemp Repo should be there.  Please check.

**Comment by tabinks** [comment]
@xiaomaogy Are you filling out this form? 
https://docs.google.com/forms/d/11T_44v0B4pn24EwuqiWAH4btUZYUWaVblDHnilyqfbE/viewform

I manually added your repo.  You should find it by using your github username.

**Comment by tabinks** [comment]
@davidcl1 @jiamaozheng @xiaomaogy Repos should all be there.  Please check and let me know if you don't find them.

**Comment by jiamaozheng** [comment]
It works. Thanks a lot,

**Comment by ceruzzi** [comment]
@tabinks Ok. I see it and i think I submitted everything successfully(by going into my HelloWorld folder on my computer and using 'git remote add origin https://github.com/uchicago-mobi/Ceruzzi-MPCS51030-Winter-2015-Assignment-1.git'... I hope thats the right way). Thanks!

**Comment by davidcl1** [comment]
I see mine as well, thanks.

**Comment by tabinks** [comment]
@ceruzzi Sounds about right.

**Comment by xiaomaogy** [comment]
@tabinks  I now see it. Thanks.
