### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by psajja** [uchicago-mobi/2015-Winter-Forum#191]
When ever I create any app and put it in background and then close the app by double clicking the home screen (in the simulator) and then swipe it in the upwards direction, my app crashes. I am trying to test the local notification when the app is closed. Is this normal ?

**Comment by psajja** [comment]
Never Mind. It works fine now. !! Thanks.

**Comment by JRam13** [comment]
You can't close your app while it's running in the simulator (when triggered from xcode), it'll crash like you said. I'm not sure why you need to test out notifications while your app is forced closed- it should be the same as if your app is open or in the background.

**Comment by psajja** [comment]
Thanks for clarifying that. I was under the impression that the local notification would have different behavior when the app is in the background as opposed to being closed.
