### ISSUE TITLE
iOS 7.1 Simulator?

### ISSUE THREAD

**Issue by mceruzzi-denodo** [uchicago-mobi/2015-Winter-Forum#196]
So, one of the central features of my app (text to speech) isn't actually supported at this time by iOS 8 simulator (just the simulator, it is supported by iOS 8 itself). It does work fine both when tested on an actual device or with iOS 7 simulator. This isn't a problem for developing the app since I can just run it with the 7 simulator, but I realized it could be a huge problem for graders.

Would it be ok to use this feature or is it a no go?

**Comment by JRam13** [comment]
This is fine, just make sure you note that on a read.me file or something. 

The same goes for accelerometer/other features that can't be used in the simulator.

**Comment by mceruzzi-denodo** [comment]
thanks!
