### ISSUE TITLE
How do you explain UIKit and Layout to designers?

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Winter-Forum#199]
I was asked an interesting iOS question at an interview. 

"Suggest you are working with several designers who know nothing about coding. How do you explain UIKit and Layout to them? "

Honestly, I didn't answer this question very well. My understanding was to explain several elements such as UIView, UILable, UITextView and others first. Then I explained how autolayout works. 

Any thought about this question?

**Comment by johnnypaper** [comment]
I would say:

"It's like this and grab a stack of different colored paper in different sizes and start layering them on top of each other.  Then put a 'view' underneath a larger one and say that is hidden."

Done.  Tutorial over.

**Comment by psajja** [comment]
UIKit = "Anything visible" & Autolayout = "Anything visible and looks good"

**Comment by tabinks** [comment]
I would say UIKit is a library of standard interface objects, designed by Apple, that the user sees and interacts with.  While Layout is the way to describe how those UIKit objects are positioned on the screen, regardless of the screen size.

**Comment by JRam13** [comment]
Damn, that's a good answer. 

You should teach this stuff.

**Comment by JRam13** [comment]
![](http://i2.kym-cdn.com/photos/images/newsfeed/000/328/491/f95.png)

**Comment by yiqin** [comment]
Thank everyone.
