### ISSUE TITLE
Who does NOT own or have access to a Mac?

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#20]
Hi,

I have noticed that several students do not own or have easy access to a Mac. If you are in this group would you please send me a message so that I can get a headcount? By access to a Mac I mean any Macintosh computer that is capable of running XCode 6 and OS X 10.8 (or higher). 

You can reply here or, if you're feeling shy, via email:
bobkanuri@gmail.com

Thank you,
Bobby

**Comment by aljc** [comment]
I don't have one.

On Sat, Jan 10, 2015 at 10:15 PM, bobby-digital-23 <notifications@github.com

**Comment by bobby-digital-23** [comment]
Here are several places where you can find decent deals on Macs:

Apple's refurbished site - you can find some great deals here. All of the products come with Apple's full  warranty and return policy.
http://store.apple.com/us/browse/home/specialdeals/mac

Apple Store for Education - depending upon which Mac you would like to purchase you instantly receive $50-100 off (sometimes more if you're getting a super high end Mac) as a student. From approximately May-Sep, Apple also throws in an extra $100 gift card.
http://store.apple.com/us-hed

Microcenter - great return policy and they occasionally have very good deals on new Macs which are as cheap, if not cheaper, as the Apple refurbished ones. They sometimes sell pre-owned Macs for very little money. However, if you go for a pre-owned Mac, please check that the hardware is capable of running the versions of OS X and Xcode needed for this course.
http://www.microcenter.com/search/search_results.aspx?Ntt=macbook

You can also find great deals on eBay, Craigslist, and through your friends/family. Do your homework before buying one this way but a well taken care of Mac will last you a long time. There were certain Macs released which were known for overheating but you can easily discover if you're about to purchase a lemon with a quick internet search. I also highly recommend that you enter the serial number of a used Mac before buying it to doublecheck if it was stolen (particularly if the deal sounds too good to be true). Checking the serial number will also tell you if there is outstanding AppleCare left on the used Mac (which is a very good thing). :)

You can check serial numbers for any Mac here:
https://selfsolve.apple.com/agreementWarrantyDynamic.do

Good luck! :)
