### ISSUE TITLE
UILabel font sizing...

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#200]
Don't know but I found this key and hopefully it helps someone else:

yourLabel.adjustsFontSizeToFitWidth = YES;

Automatic font sizing if you aren't using autoLayout, or if you are I'm sure there is  a checkbox for it or something GUIish.

Ding!

**Comment by tabinks** [comment]
There is also a % you can set to make sure that the font never falls below a range.

**Comment by JRam13** [comment]
^ This

![](http://www.qualiahealth.com/misc/autoshrink.png)
