### ISSUE TITLE
Apple Developer Provisioning Profile

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#201]
I just re-updated the class provisioning profile if you were having troubles with this...

**Comment by jiamaozheng** [comment]
I have updated one of my devices to iOS8.2, but it appears that iOS8.2 is not supported by current version of xcode. So please don't update your device's iOS to iOS8.2.

**Comment by tabinks** [comment]
Xcode has an update for 8.2 in App Store.

**Comment by jiamaozheng** [comment]
updated, thanks.
