### ISSUE TITLE
Best Practice for Global Vars

### ISSUE THREAD

**Issue by egbertc** [uchicago-mobi/2015-Winter-Forum#206]
I have a bunch of constants and functions that need to be shared across all my classes.
should I create a class like "AppUtilities.h" that holds all the constants and any utility functions and just import that class in every other class?

currently I find myself importing stuff all over the place and it's just asking for disaster.

**Comment by tabinks** [comment]
.pch file would be perfect, it's imported automatically in every file.

**Comment by egbertc** [comment]
appreciate it!
