### ISSUE TITLE
Final project - Git Inspired   launched on App Store

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Winter-Forum#207]
Hi everyone. My final project - Git Inspired launched on App Store.

https://itunes.apple.com/au/app/git-inspired-best-inspiring/id953710137?mt=8

Developers love open source projects on Github, and Bitbucket. We want to get inspired from these open source projects, instead of to use these code directly in our code. The idea of Git Inspired is to provide a place for iOS developers to share and geek out about the latest open source projects, every day.

Key features:
- Check out the latest, trending open source projects
- Vote for your favorite products
- Follow discussions and add your insight comments
- See what other's are interested in
  
  ![4 7-inch iphone 6 - screenshot 1](https://cloud.githubusercontent.com/assets/4560331/6625374/a04987fe-c8bd-11e4-8a36-de12f425929e.jpg) ![4 7-inch iphone 6 - screenshot 2](https://cloud.githubusercontent.com/assets/4560331/6625373/a047b9f6-c8bd-11e4-81d3-e9a57016926b.jpg)

Love to hear any thoughts. Thanks.

**Comment by tabinks** [comment]
Looks good.

**Comment by tabinks** [comment]
The CS Department is interested in putting this on their social media feed.   Do you mind?

**Comment by yiqin** [comment]
@tabinks That's awesome!  (btw where is their social media feed?)
