### ISSUE TITLE
Whammy Watch

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#210]
Could be a potential whammy or supreme irritation/crash if you rename your project and then try to use the copy uploaded to GitHub to make sure the project will run on other machines.

Be careful doing this.  Better yet just don't rename anything and stick with whatever you originally named the file unless you want the extra errors to debug.

**Comment by JRam13** [comment]
![](http://s.quickmeme.com/img/7a/7adf9daeb3fac200762c1ea5387ac9582df9e1932a6e41b3f829d5250dc15fc1.jpg)

**Comment by jhergott** [comment]
When you submit an app to the app store do you have the opportunity to rename it?

**Comment by tabinks** [comment]
Yes.  There is the marketing name in itunes that has nothing to do with the name of your xcode project.

**Comment by tabinks** [comment]
I though this was new apple watch idea -- whammy watch!
