### ISSUE TITLE
Office Hours - Friday @ 3:30pm(ish) Crerar

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#211]

**Comment by windyita** [comment]
Where can we find you?  Could you explain the place more explicitly?

**Comment by bobby-digital-23** [comment]
I'll be in or very close to one of the Mac Labs - CSIL 1 & 2 in the Crerar library (behind the bookstore).

Apologies - running a bit late today. Stuck in some bad traffic. It will be a little closer to 4pm. I'll stay as late as needed.

**Comment by bobby-digital-23** [comment]
http://csil.cs.uchicago.edu

**Comment by windyita** [comment]
Hi Bob, have you arrived? We can't find you.

**Comment by bobby-digital-23** [comment]
Yes I am parking on campus I will be there in approximately 5-10 minutes. sorry traffic was absolutely brutal today see you soon

**Comment by bobby-digital-23** [comment]
Found parking. Walking to Crerar.
