### ISSUE TITLE
Keywords - how to count 100 character

### ISSUE THREAD

**Issue by mattmeier** [uchicago-mobi/2015-Winter-Forum#212]
Hi,

sorry for a kind of stupid answer, but just to double-check:
I guess the keywords count of 100 characters only includes the characters of the actual words, not the commas and spaces to list them, right?

**Comment by tabinks** [comment]
you would think but no, the spaces and commas count.

**Comment by JRam13** [comment]
Andrew is correct. However, you shouldn't put spaces between your keywords!

keywords: one,two,three,four...

**Comment by mattmeier** [comment]
Ok, thanks!
