### ISSUE TITLE
No Signing Identity

### ISSUE THREAD

**Issue by mceruzzi-denodo** [uchicago-mobi/2015-Winter-Forum#213]
I wanted to test my app on my iPhone and I thought the university developer account allowed me to do that. However, whenever I try to test it on my device, I always get a "no signing identity found issue."

When I try to fix this by inputing the UChicago team and hitting the 'fix issue' button, I get "The selected team doesn't have an iOS Developer Program membership."

Any idea what's causing this?

**Comment by tabinks** [comment]
I see that you have a provisioning profile, however I do not see that you filled out the form to add a device id.

**Comment by tabinks** [comment]
Send me the UDID of you device and I'll add it.

**Comment by mceruzzi-denodo** [comment]
thanks! I just sent it through the form. I can also send it via email if that would be easier.

**Comment by tabinks** [comment]
Just email it to me and I'll do it right now.

**Comment by tabinks** [comment]
Never mind, I see it.

**Comment by tabinks** [comment]
It there...
