### ISSUE TITLE
Deal with Airplane mode

### ISSUE THREAD

**Issue by LingduoKong** [uchicago-mobi/2015-Winter-Forum#214]
When I deal with Airplane mode, can I just refuse the access of user to more detail?

**Comment by JRam13** [comment]
Can you please explain what you're trying to do? I don't get it.

**Comment by LingduoKong** [comment]
Since my app relies on api highly, it will display nothing without network and crash when I want to show details or more functions. So I would like to forbid these actions by setting buttons disable.

**Comment by tabinks** [comment]
It is fine to pop an alert saying, "This app requires an Internet connection.  Please try again when one is available."  Many apps take this approach.
