### ISSUE TITLE
Splash Screen vs launch screen

### ISSUE THREAD

**Issue by mceruzzi-denodo** [uchicago-mobi/2015-Winter-Forum#215]
The checklist says we need a splash screen.I understand why we needed a splash screen in project 7 since we downloaded data from the internet. But, If our app doesn't download any data, wouldn't the launch screen cover the entire role of the splash screen?

**Comment by susanstevens** [comment]
I was wondering something similar.  If we aren't downloading data from the internet, should we just have the splash screen stay up for some pre-determined amount of time (3 seconds or something), and then fade away?

**Comment by tabinks** [comment]
You are correct that in some apps it doesn't add any functionality, but for the projects, this is just a chance to show that you understand many design patterns and techniques.  Susan's suggestions would be fine for the project.  If anything, a smooth fade out may be considered more visually appealing than a just switching screens.

Remember that in some launch scenarios you will not see always see the launch screen.  This is only shown when the app is launched from terminated state.  If you are just in the background, you would not see this when the app becomes active in the foreground.  One example of this would be the passcode screen in the Dropbox app.  When the app launches for the first time, the passcode is shown.  However, you want this to show again when becoming active.  If not, anyone could pick your phone and open the app to see all your files.  You want to show this splash screen, not just the loading screen.
