### ISSUE TITLE
Presentation tomorrow?

### ISSUE THREAD

**Issue by yiqin** [uchicago-mobi/2015-Winter-Forum#216]
Do we have a presentation on Monday? Is everything due on  March 18th at 11:59 PM (CST) ?

**Comment by bobby-digital-23** [comment]
Yes, presentations are on Monday. We're all looking forward to seeing everybody's final projects. 😊

Not sure about the final due date/time. Dr Binkowski?

**Comment by tabinks** [comment]
Presentations tomorrow.  Repos and marketing materials due 18th.
