### ISSUE TITLE
May I ask what the NSUserPreference for "Initial Launch" is exactly?

### ISSUE THREAD

**Issue by haouc** [uchicago-mobi/2015-Winter-Forum#217]
Is this a saved data of NSDate when the first use in somewhere (such as NSUserDefault)? Does this have to be showed in preference in setting? Or show up somewhere in App? Does this Date have to be user specific? I mean save different dates according to different users (which also means we need recording the user info by the feature of login). Sorry for many questions. Thanks.

**Comment by tabinks** [comment]
It does not need to show on the Settings screen.  Just store the value and print it out in a NSLog so we know you can use NSUserDefaults.

**Comment by haouc** [comment]
Thanks.
