### ISSUE TITLE
Booth New Venture Challenge Partnership

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#220]
Hi,
I was contacted by Leah Eggers (eggers@uchicago.edu) about an opportunity to join their new venture challenge team.  

_...
I am writing to you because I am part of a team of 3 students from SSA that are competing in the Social New Venture Challenge (http://research.chicagobooth.edu/nvc/socialnvc/) at Booth. Christina Hachikian of the Social Enterprise Initiative recommended that we reach out to the department and I saw that you have expertise in mobile application development._

_Our team is working to develop a parenting app and web portal for fathers. We are looking to add another team member to help us develop the app and/or assist with back end web portal development. We are seeking a Masters student, or student with requisite skills and experience and that the student can commit to be a member of the team for at least Spring quarter. We are looking to find a new team member no later than March 30th.
..._

Sounds like a good opportunity.  There is a lot of very good exposure for the NVC and a great opportunity to be a part of (or at least build up your portfolio).  If you are interested, please email directly.

**Comment by drefiuza** [comment]
I joined an NVC team last year in a similar role. It's a good environment for learning about pitching and business models; the judges are constantly giving you critical feedback.
