### ISSUE TITLE
App looks how I want it, but NSLog yelling at my constraints.

### ISSUE THREAD

**Issue by mceruzzi-denodo** [uchicago-mobi/2015-Winter-Forum#222]
So my app looks how I intend it to. However, when I rotate it to landscape mode, NSLog complains at me because of the way my constraints are set up. Can I leave things how they are if it looks good or do I need to make it so it doesn't complain anymore?

**Comment by JRam13** [comment]
Is your intention to have your app be used in both states? If not, you can take our landscape altogether.

**Comment by mceruzzi-denodo** [comment]
Yah, I want it to be useable in both states. And at present, it is useable in both states. Portrait mode looks the way I want it, and landscape mode looks the way I want it. 

It's just that NSLog gives me: "Unable to simultaneously satisfy constraints. Probably at least one of the constraints in the following list is one you don't want."

Not sure if thats something I would get deducted for in the final submission.
