### ISSUE TITLE
Pub night shindig Thursday night @ 6pm

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Winter-Forum#225]
Come celebrate your passing/failing of ios development!

![](https://s-media-cache-ak0.pinimg.com/236x/8c/ab/d7/8cabd7d7bbd2f5b3263007689f269325.jpg)

Location: Pub at Ida Noyes
Time: 6

**Comment by bobby-digital-23** [comment]
![simpsons beer](https://cloud.githubusercontent.com/assets/10453834/6702477/2d356a58-ccfa-11e4-87d6-803673fa4420.jpg)

**Comment by drefiuza** [comment]
I'll be there!

![ibeerphone](https://cloud.githubusercontent.com/assets/1236521/6702790/83922de2-ccfe-11e4-9d4e-b1c1ad1f8de7.jpg)

**Comment by windyita** [comment]
final exam on Thurday 5:30pm...

**Comment by yiqin** [comment]
Skip the final.

**Comment by johnnypaper** [comment]
I heard this was one of the answers to the final...hopefully it helps get you some free points.

![screen shot 2015-03-18 at 12 39 37 am](https://cloud.githubusercontent.com/assets/6334967/6703274/254fb8d6-cd07-11e4-8d2a-2377f1c78cee.png)

**Comment by bobby-digital-23** [comment]
The pub is open until 12am. Come after your final! :)

Anyone who needs a designated driver - just let me know. I can't drink alcohol (severely allergic) which makes me lifelong key master. ;)

![rsz_john-cusack-ione-skye-and-eric-stoltz-in-say-anything-1024x550](https://cloud.githubusercontent.com/assets/10453834/6703688/0fad0488-cd0d-11e4-8092-a81222462691.jpg)

**Comment by tabinks** [comment]
Is it kid friendly? 😄

**Comment by JRam13** [comment]
Hide yo kids, hide yo wife.

**Comment by cheng-wu** [comment]
Have a final project report due on Friday........ 

doubt "Come celebrate your passing/failing of ios development!" Celebrate failing.....?...>.<..

**Comment by JRam13** [comment]
We don't discriminate here.

**Comment by JRam13** [comment]
Just a reminder, this is happening tonight.

I'm expecting to see everyone there, especially if you have a final coming up!
