### ISSUE TITLE
Signing up for a Free University Apple Developer Account

### ISSUE THREAD

**Issue by gitlaura** [uchicago-mobi/2015-Winter-Forum#23]
Are we able to sign up for a free student apple developer account with our student ID's now? Do we use our student ID/ email address to do this?

**Comment by xiaoyifan** [comment]
the student edu mail address is required, maybe we have to wait a few days. My personal year developer account will be over in a few days, i'm waiting for that, too.

**Comment by tabinks** [comment]
You only need to sign up for a free apple developer account.  The university accounts will be set up by me and added to your free accounts during the quarter.

**Comment by jiamaozheng** [comment]
I just registered a free apple developer account at 
https://developer.apple.com/register/index.action

**Comment by xiaoyifan** [comment]
that's not developer program

**Comment by tabinks** [comment]
Everyone should have received email from Apple about Iniversity developer program.  See issue 35.
