### ISSUE TITLE
MyAirplanePics is now available at the apple store, free download! 

### ISSUE THREAD

**Issue by jiamaozheng** [uchicago-mobi/2015-Winter-Forum#230]
https://itunes.apple.com/us/app/myairplanepics/id977891576?mt=8

![screen shot 2015-03-25 at 2 02 14 pm](https://cloud.githubusercontent.com/assets/7049849/6832978/ca6f56d2-d2f7-11e4-87da-14273119332b.png)

**Comment by bobby-digital-23** [comment]
Congratulations!!!! It's always awesome to see students publish their apps!

I'll be sure to download it and give your app 5 stars. :)

**Comment by jiamaozheng** [comment]
Great class and wonderful instructors!!! Thank you all so much!

**Comment by yiqin** [comment]
Great job!

**Comment by yiqin** [comment]
Here is a tool which you definitely want to use when publishing your app.

Screenshot Builder - Create gorgeous images for your App Store page in minutes.
https://launchkit.io/screenshots
![examples-vbcb4abc42559](https://cloud.githubusercontent.com/assets/4560331/6883776/f926066c-d593-11e4-9452-ec9eb74a9e1f.png)

**Comment by Jlipman** [comment]
Thanks yiqin! It is amazing. Is there a version for iPad screenshots also?

**Comment by yiqin** [comment]
Not yet. I think they are working on it.

**Comment by bobby-digital-23** [comment]
You might find this article helpful:
http://www.smashingmagazine.com/2015/03/04/create-effective-app-screenshots-for-app-page/

One of the apps they mention in that article - Screenshot App - does support iPad screenshots.
http://screenshotapp.e7mac.com/

**Comment by Jlipman** [comment]
Those look great, also if anyone else was looking Ray Wenderlich has some good suggestions

http://www.raywenderlich.com/71175/make-great-app-store-screenshots
