### ISSUE TITLE
"Easy Flight Check In" for southwest in now in the App Store. 

### ISSUE THREAD

**Issue by psajja** [uchicago-mobi/2015-Winter-Forum#231]
https://itunes.apple.com/us/app/easy-flight-check-in/id976418558?ls=1&mt=8

![screenshot 2015-04-02 05 41 30](https://cloud.githubusercontent.com/assets/10427273/6962740/0db5e0b8-d8fd-11e4-9f26-7ae022399472.png)

**Comment by JRam13** [comment]
Thats great! Good job.

**Comment by psajja** [comment]
Thank you

**Comment by bobby-digital-23** [comment]
Congratulations! Downloaded and given 5 stars. 😊

**Comment by psajja** [comment]
Thank you!! I appreciate it :)
