### ISSUE TITLE
Product Name, Organization Name, Organization Identifier

### ISSUE THREAD

**Issue by jdanzig** [uchicago-mobi/2015-Winter-Forum#24]
For future reference, how do we fill out the options for a new project?

Product Name: HelloWorld
Organization Name: jdanzig
Organization Identifier: edu.uchicago

OR

Product Name: HelloWorld
Organization Name: uchicago
Organization identifier: edu.jdanzig

**Comment by tabinks** [comment]
This is completely up to you.  It is strictly for internal (your own) purposes only.
