### ISSUE TITLE
Office Hours Monday at 4:00pm in Crerar

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#26]
There will be office hours Monday at 4:00pm in Crerar with Bob Kanuri.  All instructors will be also be in Ryerson ~30 minutes before class to answer any questions.

**Comment by johnnypaper** [comment]
Where in Crerar will the office hours be?

**Comment by tabinks** [comment]
Check with @bobby-digital-23 to see exactly where he'll be, but  I'm pretty sure that he'll be in the proximity of the Mac lab.

**Comment by bobby-digital-23** [comment]
Yes, either CSIL 1 or CSIL 2 - the two labs with Macs :)

http://csil.cs.uchicago.edu

**Comment by aljc** [comment]
I think there's a lab going on right now.  The only Macs available are the ones outside the CSIL rooms.

**Comment by xiaoyifan** [comment]
yeah, not many macs available right now.

**Comment by bobby-digital-23** [comment]
FYI - I am here with a student right now in the back corner and we're holding onto a few Macs.

**Comment by aljc** [comment]
Which room are you in?

**Comment by bobby-digital-23** [comment]
CSIL 2 in the back corner with two students right now

http://csil.cs.uchicago.edu

**Comment by bobby-digital-23** [comment]
I will be leaving Crerars at 5pm to help students with questions over at our classroom in Ryerson.

See you all there. :)
