### ISSUE TITLE
Shuffle Implementation

### ISSUE THREAD

**Issue by jhergott** [uchicago-mobi/2015-Winter-Forum#30]
Here is the code for the shuffle implementation from lecture...
"NSMutableArray *tmpArray = [NSMutableArray arrayWithCapacity:[self count]];

 for (id anObject in self) {
 NSUInteger randomPos = arc4random()%([tmpArray count]+1);
 [tmpArray insertObject:anObject atIndex:randomPos];
 } "

Why do you have to add 1 to [tmpArray count]?  Lets say your original array was length 3 and therefore have indices 0, 1 and 2.  When you mod any integer by 3 it should return 0, 1 or 2, correct?  I feel like adding 1 here will insert objects at indices 1, 2 or 3, but index 3 should not exist.  Am I thinking about this correctly?  Thanks

**Comment by tabinks** [comment]
arc4random(N) generates random number between 0 to N.  So to make it inclusive of N, you need to +1.
