### ISSUE TITLE
How to set the contentSize for the UIScrollView?

### ISSUE THREAD

**Issue by xiaomaogy** [uchicago-mobi/2015-Winter-Forum#32]
In the homework under the interface it says 

Add a UIScrollView using storyboard. Set the scrollview’s contentSize property to 960 x 500. By choosing this size, we are effectively creating 3 ‘pages’ in the scrollview as only 320 x 500 (i.e. the scrollview’s frame property) of the scroll view is visible at a given time. Setting the scrollview's pagingEnabled property provides this effect when swiping. Note that the contentSize an property can only be modified programmatically.

But where do we set the UIScrollView's content size? After I add the UIScrollView using the storyboard, there is no code changed in my ViewController.m file. I tried to add some code under the viewDidLoad method but it just didn't work

**Comment by JRam13** [comment]
After your view has been displayed, you can programmatically set it by calling [self.scrollview setContentSize:CGSizeMake(960, 500)]; 

*self.scrollview is the scrollview from your storyboard.

**Comment by xiaomaogy** [comment]
![screen shot 2015-01-14 at 10 03 16 pm](https://cloud.githubusercontent.com/assets/5985076/5752361/38eab750-9c39-11e4-8948-c5663a1e33a1.png)

Where should I put the [self.scrollview setContentSize:CGSizeMake(960, 500)];

I tried to push it in the viewcontroller's implementation section but it didn't work.

I just wonder after I add the scrollview, where in the code is it being declared or implemented so that I can change it.

**Comment by JRam13** [comment]
You have to declare your scroll view in your interface section (on the storyboard, control+drag scroll view into your code). Drag it either to your .h or .m file, preferably .m file because you want this to be a private property (no shared with other controllers). Once you do that, you can reference it in your code by calling self.yourScrollViewName is. 

So you would call:
- (void)viewDidLoad {
    [super viewDidLoad];
    [self.yourScrollViewName setContentSize:CGSizeMake(960, 500)];
}

**Comment by JRam13** [comment]
If you have autolayouts on, you should move this code to viewDidLayoutSubviews.

**Comment by JRam13** [comment]
You may close this if you figured this out. I don't think I have permission to close threads.

**Comment by xiaomaogy** [comment]
Thanks!
