### ISSUE TITLE
NO office hours today @ 4pm

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#34]
Hi all,

Apologies, I came down with a bad cold/flu and while preparing to come in today, just realized that I'm still running a fever (and feel like @*!%). I'd prefer not to get any of you sick. :)

Several of our other kind TAs will be holding office hours tomorrow evening at 6:30pm. 

I will do a makeup session next week, if requested.

FYI: To those of you students who have emailed me personally with course questions, please post them to the forum so that our professor and TAs also have a chance to answer your questions. I will do my best to answer your questions as soon as I am able. 

Thank you,
Bobby

**Comment by bobby-digital-23** [comment]
I will (fingers crossed for good luck) be at Crerar tomorrow, Friday, @ 6:30pm along with the other TAs. 

Best,
Bobby

**Comment by JRam13** [comment]
Hey Bobby, neither I or Julie can make it tomorrow so this would be great if you can cover for us. I'm thinking of doing a session on Monday (around 5) for those who have last minute questions.

**Comment by JRam13** [comment]
Also, I hope you feel better!

**Comment by tabinks** [comment]
Don't forget that buildings will be closed on Monday, you will need ID to get in.

**Comment by JRam13** [comment]
I thought you said our ID's work now?

**Comment by tabinks** [comment]
That is supposed to be true, but I will email Karin to make sure.

**Comment by bobby-digital-23** [comment]
Thank you for the well wishes @JRam13. 🙏

I'm going to try to do my best tomorrow because I'm assuming many students are coming. 😳

As for IDs, mine seems to have worked so far but just like any mutual fund prospectus - "past returns are no guarantee of future results" 😉
