### ISSUE TITLE
Apple University Developer Program Invites

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#35]
You should all be receiving invites for the Apple University Developer program.  Please follow the instructions if you wish to activate it.  If you do not, just ignore it.  The invites will expire in 30 days and can not be reissued, so please claim them now.

**Comment by tabinks** [comment]
![image](https://cloud.githubusercontent.com/assets/93689/5768493/faa0cf0e-9cd6-11e4-8c6a-955be7d19452.png)

**Comment by mattmeier** [comment]
Note that the email with the invite might be in your spam folders (mine was)!

**Comment by jhergott** [comment]
When I go to https://developer.apple.com/ios/videos/popupcerts.action I get an error saying 
"We are unable to process your request.
An unknown error occurred. Please try again."

Should I just give it a tomorrow?  (I already accepted the invitation)

**Comment by bdeleon** [comment]
Has anyone gotten this to work? My request is approved. I installed the certificate. There were 4 provisioning profiles available. I tried dragging all of them onto the xcode icon. My phone which I connected to my machine won't show up in the organizer. I'm not sure what I'm doing wrong.

**Comment by drefiuza** [comment]
I haven't, and am in a similar place. My request has been approved and the certificate's installed. I can select my iPhone from this menu:

![screen shot 2015-01-19 at 1 50 19 pm](https://cloud.githubusercontent.com/assets/1236521/5806804/658c4290-9fe2-11e4-8901-cb55ca4abb47.png)

I can't run my app on the phone, though. XCode says "No matching provisioning profiles found" and when I click the Fix Issue button I get the following message:

![screen shot 2015-01-19 at 1 53 30 pm](https://cloud.githubusercontent.com/assets/1236521/5806822/9f486e6e-9fe2-11e4-891e-a02105857714.png)

**Comment by tabinks** [comment]
Try changing the bundle identifier to _mobi.uchicago.whateveryouwant_.  If you are installing on a device, you need to be part of this organization.  

Let me know if this works.

**Comment by bdeleon** [comment]
I'm a little bit further now but not quite there. I haven't not been able to finish the last step to add my device. It's not listed in the list shown at https://developer.apple.com/account/ios/device/deviceList.action

I've changed the bundle identifier as suggested:
![screen shot 2015-01-19 at 10 14 01 pm](https://cloud.githubusercontent.com/assets/6578388/5812141/095af1c8-a029-11e4-91ee-e7ce1cf4f93b.png)

The build settings look fine:
![screen shot 2015-01-19 at 10 18 53 pm](https://cloud.githubusercontent.com/assets/6578388/5812154/4f57ace8-a029-11e4-9027-a47ec2b6291b.png)

But when I try to run, I see that the build succeeds and then get this error:
![screen shot 2015-01-19 at 10 19 17 pm](https://cloud.githubusercontent.com/assets/6578388/5812156/65066796-a029-11e4-9f9f-2feea10fe80b.png)

I don't seem to be able to either add my device or add the provisioning profile to it. I don't even see my device listed in the xcode organizer when it's connected.

**Comment by tabinks** [comment]
When you plug the device in, did it ask you if you want to use the device for development?

**Comment by bdeleon** [comment]
No, it never asked. The device is present in the list where all the simulators are and in Windows>Devices. Just not Windows>Organizer

**Comment by drefiuza** [comment]
I also updated the bundle identifier as suggested, and am still getting the same errors that are described in my previous post.

**Comment by tabinks** [comment]
Please see Issue #59 to fill out device registration form.  I need to register each device with Apple for the certificates.
