### ISSUE TITLE
Questions about fadeIn/fadeOut

### ISSUE THREAD

**Issue by xctom** [uchicago-mobi/2015-Winter-Forum#36]
1. We should apply fadeIn/Out effect on label or both label and imageViews?
2. What is the meaning of "in over the course of the scroll"? Because the method "-scrollViewDidEndDecelerating:" will only be triggered when the scroll is complete. What I can achieve now is: for example, I scroll from Dog to Pig, when scrolling completes, "Dog" in the label fades out and "Pig" fade in. But if we want to change the alpha attributes during scrolling, I think we may implement it in other method?

**Comment by tabinks** [comment]
Just the label needs to fade in/out.  Check out some other delegate methods of UIScrollViewDelegate to see which ones may be better able to provide feedback throughout a scroll, as opposed to just the end of the scroll.

**Comment by xctom** [comment]
Ok, I just doubt if we should do all implementation in scrollViewDidEndDecelerating. Thank you!
