### ISSUE TITLE
Assignment #2 due on January 19 or January 17?

### ISSUE THREAD

**Issue by Jerry-J-Yu** [uchicago-mobi/2015-Winter-Forum#37]
http://uchicago.mobi/sessions/session2/index.html says that Assignment 2 is due January 17, 2015 at 5:29pm. Did it mean Monday, January 19, instead?

**Comment by johnnypaper** [comment]
I do recall that he mentioned even though there is no class Monday, the assignment is due then.

**Comment by bobby-digital-23** [comment]
Correct - January 19th (not 17th) by 5:29pm please.

**Comment by Jerry-J-Yu** [comment]
Thanks!

**Comment by bobby-digital-23** [comment]
FYI - you're also always welcome to turn in the assignments earlier. 😉
