### ISSUE TITLE
New version of fadeIn/Out

### ISSUE THREAD

**Issue by xctom** [uchicago-mobi/2015-Winter-Forum#38]
Now I implement fadeIn/Out effect in -scrollViewDidScroll method and I find that there is nothing to do in -scrollViewDidEndDecelerating. Can I comment out first version in -scrollViewDidEndDecelerating and use the new version.
I wonder if it can meet the requirement of HW2.

**Comment by JRam13** [comment]
If you don't have any use for -scrollViewDidEndDecelerating, just get rid
of it altogether.

**Comment by bobby-digital-23** [comment]
Correct, keep in mind what the professor said about programming iOS. There are MANY ways of accomplishing any given task.
He showed everybody a big hint, during class, for this assignment btw...

**Comment by JRam13** [comment]
However... How would you fade in the incoming label if not with scrollViewDidEndDecelerating...?

**Comment by xctom** [comment]
I just use one label and I change properties of that label when I scroll the view. So put code in scrollViewDidScroll makes UX better.

**Comment by cheng-wu** [comment]
I think both -scrollViewDidEndDecelerating and -scrollViewDidScroll meet the requirement
