### ISSUE TITLE
Properties vs instance variables

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#39]
For those of you who would like more insight into why/when to use a property or an instance variable (aka ivar) here are two helpful resources:

http://www.bignerdranch.com/blog/should-i-use-a-property-or-an-instance-variable/

http://www.cocoabuilder.com/archive/cocoa/302343-properties-vs-instance-variables.html

**Comment by tabinks** [comment]
These are a good read and start to give some insights into best practices.  As you are discovering there are many ways to accomplish tasks in ios.
