### ISSUE TITLE
BitBucket Id Form & Users

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#4]
For those having difficulty filling out the form, you will need to be logged in with your uchicago google apps account.  This allows us to capture your uchicago id in the form.

Please add the following user ids to your assignment repos:
JRam13
tabinks
amyechiu
juliesoliman
bobby_digital

I have added a couple of additional "Getting Started" resources to the Session 1 links on the [website] (http://uchicago.mobi/sessions/session1/index.html).

**Comment by aljc** [comment]
Is it possible to complete this form without having to have a uchicago google apps account?  My uchicago account is set up so that it directly forwards all emails to my gmail account - don't really want to have to create another google account on top of this.

**Comment by tabinks** [comment]
If anyone has similar situtation, just email me you uchicago id, bit bucket id and yes/no on university developer account.

**Comment by aljc** [comment]
My UChicago id is ajchang, my bit bucket id is aljc, and yes for the
university account. Thanks!

Best,
Alice

On Tuesday, January 6, 2015, tabinks <notifications@github.com> wrote:

> If anyone has similar situtation, just email me you uchicago id, bit
> bucket id and yes/no on university developer account.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/uchicago-mobi/2015-Winter-Forum/issues/4#issuecomment-68930963>
> .
>


-- 
Alice Chang
University of Chicago 2016
Computer Science and Economics

**Comment by ronmexico15** [comment]
Could you post your email? Sorry if I missed it somewhere else on the site, but I didn't find it.

**Comment by tabinks** [comment]
abinkowski@uchicago.edu

**Comment by bdeleon** [comment]
I'm a little confused on how to structure the bitbucket repo. Are we supposed to create a singular repo  where in it it we will have folders for each of our projects (e.g. MPCS51030-2015-Winter-Assignment1-uchicagoid) or should we create a repo for each individual project? If it's the latter, are we going to have to add those user ids to each project we create?

**Comment by windyita** [comment]
When I tried to add 'bobby_digital' to my assignment repo, the system said: It's time to upgrade!
Your account needs space for 6 users to complete this action, but you are currently on the 5 user plan.
and asked me to pay money for it.
However my classmate can add the 6th person....
What's wrong?????

**Comment by mallick1** [comment]
I was able to add the following 4 ids to the bitbucket repositories? to add greater than 5 ids, i am asked to upgrade to a paid plan, any idea how to get the additional ones for free?
JRam13
tabinks
juliesoliman
bobby_digital

**Comment by tabinks** [comment]
I'll send out email about this later.  Do not sign up for paid account.

**Comment by mallick1** [comment]
Ok. thanks!

**Comment by windyita** [comment]
I met with the same problem yesterday.
Just add you .edu e-mail address to your account, and your account will automatically be upgraded.

**Comment by mallick1** [comment]
thanks windyita! turns out i had to "confirm" my email . Once i did that, it recognized my .edu address as "academic" and allowed the extra user.

**Comment by ceruzzi** [comment]
I'm slightly confused. Since we are using GitHub, does this mean we are not using BitBucket anymore, or are we still using BitBucket as well?

**Comment by tabinks** [comment]
We will not be using bitbucket anymore.
