### ISSUE TITLE
Office hours TONIGHT @ 6:30pm in Crerar Mac Lab

### ISSUE THREAD

**Issue by bobby-digital-23** [uchicago-mobi/2015-Winter-Forum#40]
I'll be holding office hours tonight at 6:30pm in Crerar in either CSIL 1 or 2. They rooms are connected and have a bunch of iMacs so you should be able to find me easily. :)

Please let me know if you will join so that I can get a headcount and plan accordingly. 

Also, post any questions you might have on this forum ahead of time as this not only gives me but all of the instructors a chance to answer your questions.

**Comment by Jerry-J-Yu** [comment]
I will be coming.

**Comment by xiaoyifan** [comment]
coming!

**Comment by bobby-digital-23** [comment]
Thanks to everybody who showed up tonight. Office hours are now officially done for today! :-)
