### ISSUE TITLE
Please clarify the due time of assignment two, thanks.

### ISSUE THREAD

**Issue by haouc** [uchicago-mobi/2015-Winter-Forum#41]
I wonder which time is the due time for assignment 2, Jan 17 (http://uchicago.mobi/sessions/session2/index.html) or Jan 19? Thanks.

**Comment by tabinks** [comment]
Assignment 2 is due at 5:29 on Monday, January 19th.  Sorry for the the confusion.  I will update the page.

**Comment by haouc** [comment]
Thank you. We don't have class on Monday, do we? Will we have a makeup class later if we don't have on Monday?

**Comment by JRam13** [comment]
No class on Monday. No makeup class needed.

**Comment by tabinks** [comment]
The course has been designed to take the holiday into account.  There will not be a makeup class.
