### ISSUE TITLE
How to use shuffle on NSMutableArray?

### ISSUE THREAD

**Issue by aljc** [uchicago-mobi/2015-Winter-Forum#43]
The shuffle we wrote is for NSArray, so when I call it on the animals object (NSMutableArray), I get the following warning: "Incompatible pointer types assigning to 'NSMutableArray *' from 'NSArray *'.  Am I supposed to typecast this object?  How do I fix this?

**Comment by JRam13** [comment]
Simply make your animal array an NSArray object.
