### ISSUE TITLE
Adding animals to array

### ISSUE THREAD

**Issue by thomkel** [uchicago-mobi/2015-Winter-Forum#44]
I'm able to create animal objects, but I can't seem to add them to the array successfully.

In ViewController.h, I set the following property:

@property (nonatomic,strong) NSMutableArray *animals;

And in ViewController.m, I put the following:

```
[_animals addObject:dog];
```

but when I debug, I see the array is nil so the objects aren't being added.

I'm sure its something obvious, but some direction would help.

Thank you.

**Comment by JRam13** [comment]
Make sure you're initializing your array! You can do this under viewDidLoad. 

alloc init.

**Comment by tabinks** [comment]
Declaring a property does not create an instance of it.  Also, you should use setters/getters when accessing properties.  Use self.animals instead of accessing instance variable _animsls directly.
