### ISSUE TITLE
How to import a sound?

### ISSUE THREAD

**Issue by aljc** [uchicago-mobi/2015-Winter-Forum#46]
Locally, my project works and plays the correct sound when I press the button, but whenever I change computers and re-clone my git directory, my mp3 files stop working.  How can I import my sounds into xcode?

**Comment by bobby-digital-23** [comment]
Please read this tutorial about app bundle asset management and let me know if it solves your issue:

http://code.tutsplus.com/tutorials/ios-succinctly-asset-management--mobile-18818

**Comment by JRam13** [comment]
Just remember every time you import an asset to your project, make sure you
have "Copy items into destination group's folder (if needed)" checked.
