### ISSUE TITLE
Button press not triggering an action

### ISSUE THREAD

**Issue by thomkel** [uchicago-mobi/2015-Winter-Forum#47]
I've created three buttons, but when pressing the buttons, no action is triggered.

I assume maybe I have to add a target programmatically, but I'm not sure how to do that.

Here's how I create the button:

```
    UIButton *button = [UIButton buttonWithType:UIButtonTypeRoundedRect];
    button.frame = CGRectMake(320*i, 50, 100, 50);
    button.tag = i;
    [button setTitle:[[self.animals objectAtIndex:i ] name] forState:UIControlStateNormal];
    [self.view addSubview:button];

    if (i == 0){
        self.button1 = button;
    } else if (i == 1){
        self.button2 = button;
    } else {
        self.button3 = button;
    }
```

here are the properties:

@property (weak, nonatomic) IBOutlet UIButton *button1;
@property (weak, nonatomic) IBOutlet UIButton *button2;
@property (weak, nonatomic) IBOutlet UIButton *button3;

**Comment by xiaoyifan** [comment]
Using this line of code to handle the problem:
[button addTarget:self action:@selector(touchEvent:) forControlEvents:UIControlEventTouchDown];

and U should create the function named touchEvent, the function will be triggered

**Comment by xiaoyifan** [comment]
BTW, the function should have a parameter (like sender) in UIButton\* format, and U can use sender.tag to distinguish which button is touched.

**Comment by JRam13** [comment]
xiaoyfan is right. However, instead of a non descriptive method name like "touchEvent", go for a more... expressive one. For example, if your button plays a sound when tapped, call your action 'playSound'.

**Comment by JRam13** [comment]
Also, I see no reason to have your buttons as a property if you are programmatically making them. 

```
if (i == 0){
        self.button1 = button;
    } else if (i == 1){
        self.button2 = button;
    } else {
        self.button3 = button;
    }
```

seems kinda redundant.

**Comment by xiaoyifan** [comment]
yeah, U can name it whatever U want~just pick a cooler one

**Comment by thomkel** [comment]
Thank you!
