### ISSUE TITLE
Office hours TOMORROW (Monday) before assignment 2

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Winter-Forum#48]
For those of you who are having trouble with the assignment, I will be hosting office hours tomorrow. I will  update this thread with the exact time and location. 

Please let me know below if you are thinking about attending. 

Jonny
Time: 4
Location: Crerar

Bob K.
Time: 3:30
Location: Crerar

**Comment by JRam13** [comment]
Bob Kanury will also be hosting office hours tomorrow.

**Comment by jdanzig** [comment]
I'll be there.

**Comment by JRam13** [comment]
Office hours posted.

**Comment by bobby-digital-23** [comment]
See you all at Crerar. Please note that the computer labs are closed today. We will use the general space next to the labs where there are a few, but not many, Macs available. Please bring your own if possible.

**Comment by mceruzzi-denodo** [comment]
I'll be there.

**Comment by JRam13** [comment]
Anybody that needs office hours, Bobby and I are here at Crerar. Just past the first set of Macs.
