### ISSUE TITLE
best practice: int or NSInteger

### ISSUE THREAD

**Issue by narvemp** [uchicago-mobi/2015-Winter-Forum#49]
Is there a convention as to which one we should use for this class?

**Comment by bobby-digital-23** [comment]
Geberally, NSInteger BUT could you provide some context on when you might want to use int?

Let me know if these posts answer your question:

http://iosdevelopertips.com/cocoa/nsnumber-and-nsinteger.html

http://stackoverflow.com/questions/4445173/when-to-use-nsinteger-vs-int

**Comment by narvemp** [comment]
Thanks for the links.

There were two things that immediately came to mind where I would have used an int
1) a 'for loop'
2) page arithmetic for fade-in/fade-out

**Comment by JRam13** [comment]
It really doesn't matter. NSInteger automatically converts your number into an int/long (depending on what architecture you're using). 

NSNumber is completely different, it is an object that can store any type of primitive number. You usually get your primitive number by:

```
int myInt = [myNumber intValue];

to convert back into an NSNumber:
NSNumber *myNumber = [NSNumber numberWithInt:myInt];
```

**Comment by bobby-digital-23** [comment]
No problem! 

In your two examples, a "for loop" and the arithmetic in assignment 2 (I'm assuming you're using a certain C function which requires an int), using an int is fine. In the latter case (if my assumption is correct), it's necessary! :-)

If that answers your question please close the thread. Thanks

**Comment by tabinks** [comment]
Also, NSInteger is compatible with 32 and 64 bit binaries.  This was a big issue when ios required 64 bit compatibility last year.  See this reference for more info:

https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Cocoa64BitGuide/64BitChangesCocoa/64BitChangesCocoa.html

**Comment by narvemp** [comment]
Thanks!
