### ISSUE TITLE
HelloWorld App Version

### ISSUE THREAD

**Issue by mattmeier** [uchicago-mobi/2015-Winter-Forum#5]
Should we use the version of the HelloWorld app as described in the lecture slides or as detailed in the Apple Handbook? There seem to be slight differences (e.g. the text field to enter a name is not in the lecture slides, but in the Apple version). Thanks!

**Comment by tabinks** [comment]
You should complete the app as described in the Apple tutorial.  The version in the slides was a shortened version that I was going to walk through if time class time allotted.
