### ISSUE TITLE
Sound truncating?

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#50]
I'm scratching my head as to why a sound only plays the first split second or so of the mp3 file and then stops...it seems as though this (inside my buttonTapped method) should do it.  Any thoughts?

 NSURL\* this_animal_sound = [NSURL fileURLWithPath:animal.soundPath];
    NSError\* audio_error;
    AVAudioPlayer *plyr = [[AVAudioPlayer alloc] initWithContentsOfURL:this_animal_sound error:&audio_error];
    plyr.volume = 2;
    plyr.numberOfLoops = 1;

```
[plyr play];
[thisAlert show];
```

I've also done error checking and seems as though everything is fine, but for some reason ARC could be releasing it?  I have no idea...

**Comment by johnnypaper** [comment]
Ok,

I have this solved, but I don't understand why this is. 

self.plyr = [[AVAudioPlayer alloc] initWithContentsOfURL:this_animal_sound error:&audio_error];

after creating the plyr in the .h file.

I'm assuming ARC destroys the allocation after the sound is played.  I still do not understand why this is necessary and the other method above truncates the sound.

**Comment by tabinks** [comment]
Without seeing the code I would check to make sure that the sound has the ability to finish playing before you show the alert.  Try and removing the alert and see if you get the sound to play to completion.  If this is the case, check to find the playback finished callbacks that are available. There are methods that will get called for the sound is done playing.

If this wasn't the case, you may want to check the sound file.there are some pretty strict rules for which sounds will play. This includes preferences in the encodings that may be a typical for a regular MP3 file.

**Comment by tabinks** [comment]
The different sound playback APIs available have different methods to override system sounds. For example, sometimes sounds will play over music or will stop music to play sounds. I'm not sure what the default behavior is for a UIAlertView but I would imagine that an alert could probably cancel all existing sounds.

**Comment by johnnypaper** [comment]
Hi Prof,

Did you see the second post here?  It makes sense to me why that works, however, it doesn't make sense to me why the first method truncates the sound.  The numberOfLoops should make the sound persist until the recording is finished playing, no?

Shouldn't the order of code executed matter here?  In the worst case the player plays the loop and then the alert pops up?

**Comment by xiaoyifan** [comment]
I think it should be the ARC's problem. If U put the plyr in the function, it will be regarded as a local variable with a lifetime that's limited to the execution of the function. Declaring it as an instance variable will keep it retained as a strong type.

**Comment by johnnypaper** [comment]
Properly put Xiao but it still should be coerced/forced into playing the full loop (for as many times as you specify) prior to destroying the allocation even with the local variable...if not, this is an ARC foul-up that needs to be changed by Apple.

**Comment by tabinks** [comment]
If your player is a property of your view controller then it will be around as long as your view controller is. This assumes that your AV audio player property is strong.  Unless there is crazy memory pressure there wouldn't be any reason that the view controller would release this property after the sound is played.  In fact a good pattern is to create one audio player per vies controller it and just send it different sound files to play.

**Comment by johnnypaper** [comment]
Thanks...that is what I did and things are smooth.  I know an AVAVP from @property will persist but it doesn't make any sense why the local allocation would disappear before finishing the sound.

I mean why would Xcode allow that to even be called locally then? Who in their right mind would use it in a local allocation if you can't play the sound...seems buggy to me.
