### ISSUE TITLE
Incorrect project name.

### ISSUE THREAD

**Issue by haouc** [uchicago-mobi/2015-Winter-Forum#53]
Hi Professor,

I accidentally used another name for my project-2 rather than "It's A Zoo in Here.". Seems it is not safe to rename it in xcode 6 (many errors have been reported on stackoverflow) and I just recognized changing name at this moment may not be a good idea, I wonder if I can keep the incorrect name and have the files in a directory which has name as "It's A Zoo in Here". Thanks.

**Comment by tabinks** [comment]
Don't worry about the name.  Just keep what you have.

**Comment by haouc** [comment]
Thank you.
