### ISSUE TITLE
To #pragma or not to #pragma (tips for organizing your code)

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Winter-Forum#54]
Hey guys, I know it's early still but I want you to start getting in the habit of writing organized and maintainable code. So I will be introducing you guys to the #pragma declaration.  

iOS classes can get very messy. As you progress throughout the course, your view controllers code will start to get longer and longer. I find it important to start thinking early about ways that you can organize your projects. Enter #pragma mark

![](https://qualiahealth.com/misc/screen1.png)

As you can see, I have used #pragma mark to separate my code into segments. Even though my viewController is over 300 lines, I can quickly find and go to any method declaration using the xcode source navigator (the red rectangle).

One more tip:
If you look on the left at the project navigator, you can see that I have grouped all of my files using the MVC name convention. All of my model objects should be inside 'Model', my views in 'Views', controllers in 'Controller' and so on. Everything in order :) 

Happy coding everyone!

For more information on #pragma: http://nshipster.com/pragma/

PS: This is totally optional and not something that is required for assignments. But hopefully something you'll use in the future.

**Comment by tabinks** [comment]
Good tip.
