### ISSUE TITLE
Check Your Assignment Repos Before Due Date

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#55]
Once you have finished you assignment and pushed it to your repo, please take a second to `git clone` it locally and test that you have included all the necessary files.  

We are already seeing homework submitted where files are linked but not included in the project.  Make sure that when you add resources to a project that you checkout 'Copy Files to Project' so they are included in the bundle.

We are grading what is submitted in the repo "as submitted".  It is your responsibility to ensure that the project contains all the files and runs as you expect.  The best way to do this is to clone it and check it to make sure there were no omissions.

**Comment by jhergott** [comment]
If we download the zip file for the project and test it will this accomplish the same thing? Not confident I cloned correctly

**Comment by tabinks** [comment]
Yes, this will accomplish the same thing.  The idea is that what you have uploaded is a completely self-contained project.

The git commands to clone locally are as follows:
- Change directory to one other than the original problem (e.g. /tmp).  This would download your project to /tmp/.

```
cd /tmp;
git clone your-repo-address
```
- You can fid the URL to clone your repo here:
  ![uchicago-mobi_danakatz-mpcs51030-winter-2015-assignment-1](https://cloud.githubusercontent.com/assets/93689/5803333/2149c81a-9fc3-11e4-9635-6250ed8d324b.png)

**Comment by mceruzzi-denodo** [comment]
Is there any way to mitigate if we accidentally did not submit the first week's project correctly?

**Comment by alextsu** [comment]
Like ceruzzi, I'd like to clarify with you, Andrew, if it's possible to excuse instances of this mistake from the first week's homework.

**Comment by tabinks** [comment]
If anyone had issues on this from first assignment, please see me.
