### ISSUE TITLE
Assignment 3 is Posted on Website

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#57]
Assignment 3 is posted on the website: http://uchicago.mobi/sessions/session3/index.html

**Comment by yiqin** [comment]
Do we have to follow the exact way in the Apple tutorial?   There are multiply ways to do it. Or make sure the project uses the reused tableviewcell?

**Comment by tabinks** [comment]
Yes.  Follow it as written.
