### ISSUE TITLE
University Developer Device Registration

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#59]
Please register each device you would like to use for development as part of the University Developer Device Registration: http://goo.gl/forms/keJcQWacx5

You may fill out the form multiple times if you want to use multiple devices.

**Comment by tabinks** [comment]
For anyone who registered their device go the developer center and download the iOS Provisioning Profile named "MPCS53010-2015-Winter".  Drag that into Xcode and see if it works.

Bryan DeLeon: Your device id was 2 characters short, please go back and fill it out again.

**Comment by jhergott** [comment]
This worked for me

**Comment by tabinks** [comment]
Yeah!  Thanks for letting me know.

**Comment by jiamaozheng** [comment]
Great that the system works for me too.

**Comment by drefiuza** [comment]
Success! Thanks!

**Comment by emondai** [comment]
I wasn't able to get mine to work. Has my device been registered yet? Please let me know. Thanks!

**Comment by gitlaura** [comment]
I used the wrong UDID the first time I submitted the form. Just re-submitted!

**Comment by tabinks** [comment]
I just approved the latest round of devices.  Download the provisioning profile named `MPCS53010-2015-Winter`

**Comment by alextsu** [comment]
Wondering if anyone happened across this issue when trying to get the provisioning profile to work. Seems like I've joined the UChicago team, but I'm still missing a signing identity. 

![screen shot 2015-01-30 at 11 05 30 pm](https://cloud.githubusercontent.com/assets/6432040/5986880/81b9594e-a8d4-11e4-8227-01ca5510616b.png)

![screen shot 2015-01-30 at 11 04 04 pm](https://cloud.githubusercontent.com/assets/6432040/5986874/5f722fd2-a8d4-11e4-98f8-086b73d6535a.png)

**Comment by egbertc** [comment]
@tabinks I just added a recently acquired iPad to the google form. Any way you can put it on the list?

**Comment by tabinks** [comment]
ill see if I can add it.  Stay tuned
