### ISSUE TITLE
Your grades

### ISSUE THREAD

**Issue by JRam13** [uchicago-mobi/2015-Winter-Forum#63]
If you have not done so, your grades will be in a new branch called 'grade' under your project. I suggest you check back periodically since I don't believe you get an email (unless you're watching your own project ?). 

![](https://qualiahealth.com/misc/grades.png)

**Comment by kaiyuand** [comment]
Has everybody already get your grade of hw2? Why I still get no result?

**Comment by JRam13** [comment]
Most of the students have gotten their assignment 2 grades. Please be patient. Allow up to a week for your assignments to be graded. 

Be cognizant of the fact that we have to go through everyone's code and write up comments, which takes some time.

**Comment by kaiyuand** [comment]
Ok, Thank you~I just want to make sure if everybody has got it.

**Comment by JRam13** [comment]
Please note that it is your responsibility to make sure you're turning in your assignments properly and on time. We have a few students that have not turned in any assignments. If you are one of the students that are missing grades or have 0's on assignments, please come talk to us ASAP. 

It is also your responsibility to be proactive on this issue. Don't wait for us to bring this to your attention.
