### ISSUE TITLE
Question page 77 of Tutorial

### ISSUE THREAD

**Issue by johnnypaper** [uchicago-mobi/2015-Winter-Forum#64]
Just a question, but these cells are static and still show up which seems to contradict the tutorial here:

![screen shot 2015-01-22 at 3 58 03 pm](https://cloud.githubusercontent.com/assets/6334967/5865475/42260e2a-a24f-11e4-8b6b-437fb7bc0e82.png)

If the Table View of the To-Do List scene is changed back to Dynamic Prototypes, the cells will be empty but they still are not dynamic in the sense that the number of cells as prototypes is equivalent to the number you have added under the table view.  

Also, the three methods that are supposed to be implemented (I'm assuming outta-the-box) are not implemented.  I suppose I'll go back and check the tutorial.

Am I missing something here?

**Comment by mattmeier** [comment]
I actually have the same outcomes as you. I just went ahead with the tutorial, but don't know yet, whether there will be any errors later on...

**Comment by johnnypaper** [comment]
OK, if this occurs with anyone else, make sure that you are in the iOS -> Source when creating your files.  I had been using XCode for another project and was using OS X -> Source when creating a Cocoa Touch Class.  Now the methods are there.

**Comment by mattmeier** [comment]
Oh, I actually did the same (don't know why I was on OS X though...) - thx for the heads up!

**Comment by johnnypaper** [comment]
Yep that fixes it.  Methods are available straight away and data isn't present.
