### ISSUE TITLE
OS for Homeworks - Mavericks or Yosemite?

### ISSUE THREAD

**Issue by dannoel40** [uchicago-mobi/2015-Winter-Forum#7]
I would like to confirm that I am using the correct version of OS X for our homework. I believe there is agreement that we should use XCode version 6.1.1 (6A 2008a)

I believe the latest version of OSX is Yosemite 10.10.1. My notes from class last night say to work with OSX Mavericks 10.9. The requirements section of the class website says we need access to OSX 10.8 Mountain Lion. 

I would appreciate some clarity on the operating system and version of XCode that will be used for compiling assignments.  While compile errors won't be an issue for simpler applications, a different OSX version might be a problem as our applications grow more elaborate down the road.

**Comment by tabinks** [comment]
The most important thing is that everyone uses the latest version of Xcode (6.1).  This will run on both 10.9 and 10.10.  There is some functionality that is only available in 10.10 (e.g. handoff) which we will discuss later in the course.

As long as your assignments compile in Xcode 6, any homework submissions using either 10.9 or 10.10 will fine.
