### ISSUE TITLE
Does Anyone needs a partner for the App review ?

### ISSUE THREAD

**Issue by psajja** [uchicago-mobi/2015-Winter-Forum#73]
Hi - Let me know if anyone needs a partner for the app review. Since I will be traveling between 3 - 11 Feb, I will not be available during that time. Thanks.

**Comment by bdeleon** [comment]
I'm looking for a partner as well. I also will be traveling from feb 6-8 and feb 12-15 but can usually work most nights that aren't those dates.

**Comment by psajja** [comment]
That sounds good. Shoot me an email : psajja@uchicago.edu. When the app sign in sheet is out I can put you down for it. Thanks. - Pavan Sajja
