### ISSUE TITLE
Devices Added

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#76]
I just approved the latest round of devices. Download the provisioning profile named `MPCS53010-2015-Winter` from apple developer web portal.

If it doesn't work for you, let me know by replying in this issue.

**Comment by ronmexico15** [comment]
Professor,

I should have jumped on this earlier, but I don't think my device is registered. I just submitted an application on the google form.

Sorry about bringing this up so late.

Thanks.
