### ISSUE TITLE
Confusion about description of HW4

### ISSUE THREAD

**Issue by xctom** [uchicago-mobi/2015-Winter-Forum#78]
I read through the whole requirement about HW4 and I think there must be some thing wrong.

The requirement said: "UITabBarController contain three tabs, corresponding to three custom view controllers: IssueTableViewController, IssueDetailTableViewController, CircleViewController."

But there appears another tableViewController: AllIssuesTableViewController, which is not mentioned above.

So I think the structure should be like this:
**UITabBarController -> AllIssueTableViewController, IssueDetailTableViewController, CircleViewController**

**IssueDetailTableViewController-> IssueDetailViewController**

The "IssueTableViewController" is actually "AllIssueTableViewController".
Is my understanding right?

**Comment by tabinks** [comment]
Yes, you are correct.  I will update the assignment description.
