### ISSUE TITLE
Video Resource Added to Assignment

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#79]
This video may be useful for implementing man of the features of this assignment.   For example, at 15:20 there is a demonstration of creating custom table view cells.  There are some parts that do not apply, such as persisting data.  

It was created using a previous version of Xcode, but the concepts are still valid.

https://www.youtube.com/watch?v=WNSpNnmVpps

**Comment by drefiuza** [comment]
Hey Andrew, 

This link looks like it's for a different video.

Andre

**Comment by JRam13** [comment]
Here it is: https://www.youtube.com/watch?v=dQw4w9WgXcQ

**Comment by drefiuza** [comment]
Great video, thanks Jonny!

**Comment by tabinks** [comment]
I've also added a few more screenshots to the assignment description to clarify some points.

**Comment by tabinks** [comment]
Classic :+1: 

Here is the link:  https://www.youtube.com/watch?v=edVRFBa8Wns
