### ISSUE TITLE
API Rate Limit Exceeded

### ISSUE THREAD

**Issue by jhergott** [uchicago-mobi/2015-Winter-Forum#82]
I am getting the error...

"message = "API rate limit exceeded for 205.178.74.72. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)";"

My app was working fine for a long period of time and then started crashing on me when I ran it.  I'm assuming this error means I just ran it too many times and github did not like that .  Does this seem to be the case?

Note: https://developer.github.com/v3/#rate-limiting  
Seems like github allows 60 requests per hour for an IP address.

**Comment by tabinks** [comment]
You can check you rate by sending this:  

```
curl -i https://api.github.com/users/username
```

The response is:

```
HTTP/1.1 200 OK
Server: GitHub.com
Date: Sun, 11 Nov 2012 18:43:28 GMT
Content-Type: application/json; charset=utf-8
Connection: keep-alive
Status: 200 OK
ETag: "bfd85cbf23ac0b0c8a29bee02e7117c6"
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 57
X-RateLimit-Reset: 1352660008
X-GitHub-Media-Type: github.v3
Vary: Accept
Cache-Control: public, max-age=60, s-maxage=60
X-Content-Type-Options: nosniff
Content-Length: 692
Last-Modified: Tue, 30 Oct 2012 18:58:42 GMT

{
  "login": "defunkt",
  "id": 2,
  "url": "https://api.github.com/users/defunkt",
  "html_url": "https://github.com/defunkt",
  ...
}
```

Look for X-Rate-Limit Remaining.

**Comment by alextsu** [comment]
I notice on the API Documentation here: https://developer.github.com/v3/#authentication that if you authenticate, you can make up to 5000 calls per hour to the api versus 60 calls per hour. I couldn't figure out how to use the token GitHub generated for me. Does anyone have any idea how to get this to work?
