### ISSUE TITLE
App Case Study Signup Deadline

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#83]
For those of you who haven't signed up for the app case study, there is a good chance you will be presenting this week, as most of the time slots in later weeks have been assigned.

Please fill out the form with you and your partners names ASAP.  **If you do not fill out the form by Thursday, January 29th at 12:00pm you will receive a zero for the study.**  No exceptions will be made.

Here is a link to signup form: http://goo.gl/forms/DaPP5sf81K

**Comment by mattmeier** [comment]
If one of the 2 people fills out the form, this is sufficient, right?

**Comment by tabinks** [comment]
If your name is somewhere on the form, you are fine.  I see yours.

**Comment by cheng-wu** [comment]
I just submitted right now, but January 28th 12pm.... is it noon today??.. or tonight? Thank you!

**Comment by narvemp** [comment]
I just wanted to make sure you received my form submission as well.

**Comment by tabinks** [comment]
The submission is due the 29th.

**Comment by tabinks** [comment]
@narvemp Got it.

**Comment by tabinks** [comment]
If you can't find a partner, just sign up as an individual and I will try to do some match making.
