### ISSUE TITLE
Storyboard Fix for Assignment

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#9]
The Apple write-up doesn't discuss Size Classes, a new iOS8 feature that allows you to develop for multiple screen sizes with the same storyboard.  You will notice that you UILabel will not be centered properly when you run in the simulator.  For this assignment, turn off autolayout and size classes in the storyboard.  
* Click on the storyboard file
* Tap the "File Inspector" in the utility pane
* Uncheck the options for "Use Auto Layout" and "Use Size Classes".  

See the screenshot below:
![screenshot 2015-01-07 11 33 40](https://cloud.githubusercontent.com/assets/93689/5650152/6028a986-9661-11e4-92d1-c67298b1ce50.png)

**Comment by jhergott** [comment]
I was struggling with this, thanks for the note.

Now when I run the simulator for iPhone 5 or 5s it looks how I would expect.  However, it is still not centered for iPhone 4, 6 and 6 plus for me.  Is this ok for hw 1?

**Comment by mattmeier** [comment]
Same: when I have the option "Inferred" for "Simulated Metrics" (View Controller-->Attributes Inspector) I do not get automatic adjustment, and have to specify which screen size I want to have to get correct alignments.

**Comment by tabinks** [comment]
For this assignment, it is ok if the text is not centered for every device.  We will discuss this all later.  The most important thing is that the text gets on the screen for now.

Another thing you can do to ensure that the text gets centered is to turn off autoresizing masks.  Autoresizing masks were the old way to make views adapt to different orientations and sizes.  Just tap on the red bars to toggle on/off.  See below:

![main_storyboard](https://cloud.githubusercontent.com/assets/93689/5650670/190c9e22-9666-11e4-9d9d-1f704550af46.png)

**Comment by JRam13** [comment]
![image](https://cloud.githubusercontent.com/assets/3259292/5664840/0e02c6ce-9719-11e4-9225-5e2bb0613c1c.png)

**Comment by narvemp** [comment]
This repo seems like it would be useful in the future for layouts.

https://github.com/smileyborg/PureLayout

**Comment by tabinks** [comment]
Thanks for sharing.
