### ISSUE TITLE
Case Study Schedule

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/2015-Winter-Forum#90]
Here is the assigned case study schedule.  If you have any issues with your assigned date, please try to find another group to switch with.  Please see issue #84 for information about the format.

| Name | Name | Assigned Week |
| --- | --- | --- |
| Hao Zhou | Lingduo Kong | Week 5 |
| Jiaming Dong | Mu Du | Week 5 |
| Yi Qin | Michael Ceruzzi | Week 5 |
| Alice Chang | Helen Wang | Week 6 |
| Jerry Yu | Jocelyn Zhang | Week 6 |
| Laura Rokita | Susan Stevens | Week 6 |
| Yan Yang | Kaiyuan Duan | Week 6 |
| Andrea Wilson | Manish Mallick | Week 7 |
| Chen Xu | Mingyang Yu | Week 7 |
| Dana Katz | Jonathan Danzig | Week 7 |
| Jaeyoung Christopher Kang | Yecheng Li | Week 7 |
| Alexander Tsu | Matthias Meier | Week 8 |
| Andre Marques | Brad Saterfiel | Week 8 |
| Pavan Sajja | Bryan DeLeon | Week 8 |
| Zheng Cai | Zezhou Wu | Week 8 |
| Jake Hergott | David Lee | Week 9 |
| Jonathan Lipman | Thomas Kelly | Week 9 |
| Narendra Vempati | Conor Egbert | Week 9 |
| Mohammad Emon Dai Ali-Akbar | Casey McCanna | Week 9 |
| Blake Shapiro | Corey Whiting | Week 10 |
| Cheng Wu | Jiayang Tong | Week 10 |
| Yifan Xiao | Yuan Gao | Week 10 |
| Zhong Wang | Jiamao Zheng | Week 10 |

**Comment by tabinks** [comment]
Please send me an email with your slides before your presentation date so I can have them loaded up for class.  Unless you have some fancy animations that you want to show, send as a pdf.

**Comment by jhergott** [comment]
David and I are on there twice for week 9 and 10.  We'll take week 9 if that works.  Thanks

**Comment by haouc** [comment]
Lingduo and I have been counted twice in the first week. Please remove one of them. Thanks.

**Comment by haouc** [comment]
Professor, may I ask if there is any requirements for how our two-person team splits the presentation? My understanding is each of us covers some of points you listed in post #84. Please correct me if I am wrong.

**Comment by tabinks** [comment]
It is up to you how you want to split up the work.  As long as you cover the material collectively, it doesn't matter.

**Comment by tabinks** [comment]
@jhergott That is fine.  You can present in week 9.

**Comment by tabinks** [comment]
Does anyone is week 7 want to switch to week 10?
