### ISSUE TITLE
Trouble storing JSONs as NSMutableArray

### ISSUE THREAD

**Issue by alextsu** [uchicago-mobi/2015-Winter-Forum#93]
Hey gang,

I'm having a bit of trouble storing the JSONs returned as NSMutableArray. Based on my NSLog, I can get the JSONs just fine, but I get stuck when matching the correct key to store data into arrays.

Here's the line:
self.gitHubFeed = [NSMutableArray arrayWithArray:[results objectForKey:@"{somethingGoesHere}"]];

Currently I get "unrecognized selector sent to instance. What should the above {somthingGoesHere} be?

**Comment by tabinks** [comment]
`NSJSSONSerializer` will return an array if the data is an array.  `objectForKey` doesn't work on `NSArray` so thats why you are getting the error.
