### ISSUE TITLE
Warning:a 60x60@2x app icon is required for iPhone apps targeting iOS 7.0 and later

### ISSUE THREAD

**Issue by aljc** [uchicago-mobi/2015-Winter-Forum#95]
I'm trying to add an app icon, and it keeps on throwing me this warning.  The app icon is showing, but even when I try to import 60x60 versions, the warning doesn't go away.  How can I fix this?

**Comment by tabinks** [comment]
A 60x60@2x should be 120px x 120px.  Is your image this size?  It may not be allowing it since it is not the correct dimension.

**Comment by tabinks** [comment]
More importantly, you should be targeting iOS8.  I will mention this in class, but we will always be targeting the latest version on the SDK.
